### ISSUE TITLE
ouster_ros with .bag file "hostname"?

### ISSUE THREAD

**Issue by mrgransky** [ouster-lidar/ouster_example#103]
Hi,
I am trying to work with ouster_ros from already recorded sample sensor bag file provided [here](http://data.ouster.io/sample-data-1.12/index.html), but in the following command, it asks for `hostname` which I do not know what to provide.

`roslaunch ouster_ros os1.launch replay:=true os1_hostname:=<os1_hostname>`

Cheers,

**Comment by mohit-khosti** [comment]
hostname is the IP address of the Ouster LiDAR sensor

**Comment by mrgransky** [comment]
so what's that IP address ?
I only get .bag file! no LIDAR sensor

**Comment by mrgransky** [comment]
@zuzi-m  Thank you very much. 
It helped me a lot.

**Comment by zuzi-m** [comment]
@mrgransky if you don't have any more questions or problems regarding this issue, you can close to mark it as resolved :)
