### ISSUE TITLE
Quality of Intensity/Range/Noise images

### ISSUE THREAD

**Issue by dcazzato** [ouster-lidar/ouster_example#104]
Hello,

I am able to receive and visualize the intensity, noise and range images while operating with the ROS node. 

Obtained output has many horizontal lines around any vertical shape of the images, with much worst quality than in the data published in your videos. As an example, I attach some image (in order intensity, noise and range image). For example, the black border where I added an arrow has a very tangible sawtoothed shape.

Is there any way to improve this output, is it a sensor issue? Please note that I already tried with different lidar_mode (these images are taken while working at 1024x20), scan_dur_ns, as well as with Ouster Studio.

Thank you,

![INT_left0062](https://user-images.githubusercontent.com/24248709/63691470-93b9c200-c80f-11e9-93fc-ffd42de4e1aa.jpg)
![NOISEleft0062](https://user-images.githubusercontent.com/24248709/63691483-9c11fd00-c80f-11e9-9118-2097afaf3f12.jpg)
![RANGEleft0062](https://user-images.githubusercontent.com/24248709/63691490-a207de00-c80f-11e9-925a-8eb93eb68785.jpg)
![e](https://user-images.githubusercontent.com/24248709/63691966-e9429e80-c810-11e9-8ec5-2e8f0f563f9a.jpg)

**Comment by dcazzato** [comment]
Hi, first of all, thank you for your reply. I acquired the same 3 images outdoor and results are much better in terms of intensity and depth. Anyway, the noise image has still an appearance like in the image attached. I am wondering if this output is standard.

![left0053](https://user-images.githubusercontent.com/24248709/63842889-c38ad600-c985-11e9-99b0-0fe1e289526c.jpg)

**Comment by dgarbuzov** [comment]
That could be normal depending on the environment. We'll be releasing some sample code for post-processing the ambient and intensity images to address some of these issues soon.

**Comment by TongxingJin** [comment]
> That could be normal depending on the environment. We'll be releasing some sample code for post-processing the ambient and intensity images to address some of these issues soon.

Hi, have you ever released something to show how to post-process the ambient and intensity images up to now?

**Comment by Samahu** [comment]
@TongxingJin I think dmitrig was referring to the [image_processing module](https://github.com/ouster-lidar/ouster_example/blob/master/ouster_client/include/ouster/image_processing.h) please check it it out.

**Comment by TongxingJin** [comment]
> @TongxingJin I think dmitrig was referring to the [image_processing module](https://github.com/ouster-lidar/ouster_example/blob/master/ouster_client/include/ouster/image_processing.h) please check it it out.

Hi Samahu, thanks for your reply, it helped me a lot. I think the laser emitters have different magnitudes of power and the corresponding receivers have different levels of sensitivity, that's the main reason for the artifact line in different rows of ambient and intensity images, right?

**Comment by patripfr** [comment]
@TongxingJin I have also developed a tool to remove these line artifacts from the ouster images, you can check it out here:
https://colab.research.google.com/github/ethz-asl/COIN-LIO/blob/main/scripts/artifact_removal.ipynb
More info about it can be found in the related publication: https://arxiv.org/abs/2310.01235
