### ISSUE TITLE
Ouster Client Incorrect JSON Library Name in Package.xml

### ISSUE THREAD

**Issue by DangitBen** [ouster-lidar/ouster_example#115]
In ouster_client's package.xml there is a dependency on jsoncpp. Rosdep fails when trying to install this because it does not match the name of the library entry in the [rosdep base.yaml](https://github.com/ros/rosdistro/blob/master/rosdep/base.yaml#L2331).

**Comment by mrgransky** [comment]
Try to replace:
```
<build_depend>jsoncpp</build_depend>
<exec_depend>jsoncpp</exec_depend>
```
with:

```
<build_depend>libjsoncpp</build_depend>
<exec_depend>libjsoncpp</exec_depend>
```

**Comment by DangitBen** [comment]
@mrgransky  I did. You can see the pull request I made quite a while ago with those exact changes.

**Comment by dgarbuzov** [comment]
Merged the fix
