### ISSUE TITLE
Nonsense in Visualizer's README

### ISSUE THREAD

**Issue by juzzlin** [ouster-lidar/ouster_example#117]
In the README it says:

`    Using Fedora: sudo apt-get update yum install vtk-devel.x86_64 eigen3-devel.noarch`

This cannot be right?

**Comment by blin4444** [comment]
`sudo apt-get update` should be in the line above.

**Comment by dgarbuzov** [comment]
Looks like a typo, should be just `sudo yum install ...`

Thanks for pointing this out!
