### ISSUE TITLE
Selecting the Azmuth and the altitude angle

### ISSUE THREAD

**Issue by Chenweng1** [ouster-lidar/ouster_example#124]
Hi,

Does anyone has the database which says how to use the altitude and the azimuth angles of the LiDAR(OS1-16). Can anyone please help me on this issue like how to calibrate the angles using the "get_beam_intrinsics" command? I am getting 64 values for the altitude angles and 64 for the azimuth angles. How I can use them for calibrating the point clouds ?My sensor model is (OS1-16-D-13).

Any help will be very appreciated.

Thanks 
Weng

**Comment by bromeara** [comment]
The values are already used to make the xyz lookup table in [os1_cloud_node.cpp](https://github.com/ouster-lidar/ouster_example/blob/master/ouster_ros/src/os1_cloud_node.cpp) by using the OS1ConfigSrv and then are called using the make_xyz_lut function. So those values are already used if you are using this node.
