### ISSUE TITLE
Firmware v1.13

### ISSUE THREAD

**Issue by JacisNonsense** [ouster-lidar/ouster_example#125]
Howdy all,

I noticed that the most recent commit to master was for firmware v1.12. With v1.13 now released, is there any plan to add support for the newer firmware version?

**Comment by zuzi-m** [comment]
The v1.13 is still compatible with the code here, there are no breaking changes. There is some extra functionality in the newer version but as far as I know it's nothing really related to or useful in this minimal client implementation.

**Comment by dgarbuzov** [comment]
There shouldn't have been any interface changes in 1.13 affecting the example code here
