### ISSUE TITLE
SLAM algorithm for Osuter OS1

### ISSUE THREAD

**Issue by mrgransky** [ouster-lidar/ouster_example#129]
Hi,

Does anyone know an open source SLAM algorithm already implemented for Ouster Raw data?

Cheers,

**Comment by bromeara** [comment]
If you mean the output of this driver then check google cartographer, If you mean raw UDP packets I don't know but I doubt it.

**Comment by mrgransky** [comment]
I compiled google cartographer but I do not know if online implementation of this also exist?
Now I first record a rosbag file and run cartographer. What I want is to run both simultaneously!

**Comment by bromeara** [comment]
This is more related to cartographer help than ouster help. I'm not sure what you mean run both simultaneously, normally with ros you just run things in multiple terminal instances. There is this page https://google-cartographer-ros.readthedocs.io/en/latest/assets_writer.html but if you want to know more about what cartographer is doing the wiki and the launch files are going to be the best place to look.

**Comment by mrgransky** [comment]
What I meant was a single `file.launch` which brings up both _os1_ and _cartographer_ simultaneously and start mapping online in RVIZ as my cart equipped with os1 is moving in the environment!

**Comment by bromeara** [comment]
you can just add the os1 code to your cartograther launch file with the xml tags <include file="$(find ouster_ros)/os1.launch> <args name="os1 args" value="os1 values"/> </include> The details of the roslaunch format can be found here http://wiki.ros.org/roslaunch/XML

**Comment by adityarath302** [comment]
I tried with Lego-loam .It works but without the IMU just the point clouds.

**Comment by dgarbuzov** [comment]
Unfortunately, we currently don't provide a sample SLAM implementation

**Comment by YiChenCityU** [comment]
> I tried with Lego-loam .It works but without the IMU just the point clouds.

Hi, I also use the ouster lidar for lego_loam. However I meet this error about TF. Do you know how to fix it ? Thanks very much.
![Screenshot 2020-07-28 16:53:42](https://user-images.githubusercontent.com/12424523/88643549-6860e680-d0f4-11ea-8e33-444db4f87736.png)

**Comment by adityarath302** [comment]
Yes I am also getting this issue when i want to vizualize lidar data in RVIZ.Can anyone help regarding this.

**Comment by bromeara** [comment]
http://wiki.ros.org/tf#view_frames use this package. You need to ensure there is a connection between base_frame and map
