### ISSUE TITLE
IMU in NED?

### ISSUE THREAD

**Issue by bochen87** [ouster-lidar/ouster_example#13]
Hi,

Could it be that your IMU is publishing in the NED convention? ROS uses ENU convention.
![image](https://user-images.githubusercontent.com/23016719/45639048-38376e00-baaf-11e8-9576-d21c749c60a1.png)

**Comment by kajep09** [comment]
I would also like to get some additional information about the IMU. Can you give us the proper transformation between the IMU frame and the Lidar frame? Are the exactly co-located, are they rotated compared to each other etc? This would help tremendously in using your lidar and/or your published data sets with existing ROS nodes, e.g. for SLAM.

**Comment by andre-nguyen** [comment]
@kajep09 You could probably just move the lidar around to guess approximately how the axes are oriented but really you need a calibration procedure as even if they gave you the specs of how the IMU is oriented, it will vary due to mechanical assembly errors.

**Comment by snakehaihai** [comment]
Its same as VectorNav vn100 and xsense MT 300.  standard NED

**Comment by dgarbuzov** [comment]
The latest update publishes a tf2 transform for the IMU frame. Let us know if you run into any more issues.
