### ISSUE TITLE
How to remove the heat sink of OS1?

### ISSUE THREAD

**Issue by YiChenCityU** [ouster-lidar/ouster_example#130]
![887182112](https://user-images.githubusercontent.com/12424523/69844441-3b2f1080-12a7-11ea-8ff5-3c55e021c7ff.jpg)

**Comment by dllu** [comment]
It is not possible. The new version will have a removable cap but the one you have does not have the removable cap.

![pic](https://cdn2.hubspot.net/hubfs/5054152/OS1-flattop_2.jpg)

Please note that the OS1 may overheat without the heatsink so it is not recommended to operate it without the heatsink.

**Comment by YiChenCityU** [comment]
Thanks very much. When can I buy the new version OS 1?

**Comment by k-mohit** [comment]
> Thanks very much. When can I buy the new version OS 1?

The OS1 series with the new modular cap is available to purchase now.
