### ISSUE TITLE
Is there a way to construct a range image directly without going to pointcloud first?

### ISSUE THREAD

**Issue by versatran01** [ouster-lidar/ouster_example#132]
I want to construct a range image directly from the packet without converting them to point cloud first.
What I don't understand is that there seems to be an azimuth offset for each beam within a column, so there is no single azimuth angle for each column, rather 64 different ones.
I can't just put the raw range data into the range image because they are acquired at different azimuth angle, right?

**Comment by versatran01** [comment]
And also I cannot wrap my head around how does a single firing of the laser generate one column of data, due to the offset (beam_azimuth_angle)

**Comment by arunumd** [comment]
I am interested in an answer to the first question in this thread.

**Comment by kairenw** [comment]
Hi @arunumd please open a new ticket for new questions if an issue is already closed, thanks! Feel free to link as needed to closed issues in your new ticket
