### ISSUE TITLE
Split into three separate repositories

### ISSUE THREAD

**Issue by s-hemer** [ouster-lidar/ouster_example#134]
... so people can better choose to i.e. only have the client lib for own projects (of course moving and preserving history).

**Comment by mrgransky** [comment]
so what was an issue in here? :)

**Comment by s-hemer** [comment]
The issue or the suggestion is to split the content of this "_example" repo into three separate git repos (client, ROS inf, visualisation). Just as the the title says. Most people will only need the bare driver (which the "_client" folder provides), no ROS, no vis.

**Comment by dgarbuzov** [comment]
Yep, we're planning on doing this asap
