### ISSUE TITLE
I got an error while building...

### ISSUE THREAD

**Issue by JongMinLee86** [ouster-lidar/ouster_example#135]
![Screenshot from 2019-12-12 16-18-00](https://user-images.githubusercontent.com/18351799/70690910-18ffae80-1cfb-11ea-8298-f15e6c1d2730.png)

I got an Json error while building...
my system is ubuntu 14.04

**Comment by mrgransky** [comment]
you do not seem to have jsoncpp installed on your machine!
Follow [here](https://linux.tips/programming/how-to-install-and-use-json-cpp-library-on-ubuntu-linux-os)!
