### ISSUE TITLE
I wanna run OS1-64 in ubuntu 14.04 ros-indigo

### ISSUE THREAD

**Issue by JongMinLee86** [ouster-lidar/ouster_example#136]
i wanna build ouster-example in my environment (ubuntu 14.04 ros indigo)

i got an error while building about json cpp library ...

Any comments or word is truly helpful.

**Comment by mrgransky** [comment]
Follow [this](https://github.com/ouster-lidar/ouster_example/issues/135#issuecomment-573029994) perhaps!
