### ISSUE TITLE
Height estimation

### ISSUE THREAD

**Issue by ethan20120** [ouster-lidar/ouster_example#140]
Hi ,

Can anyone please correct me if I am wrong that if I use the Lidar on the top of a car should I also consider the vehicle height from the ground while estimating the elevation of an object ? And the section 4.4 of the ouster software guide suggest to use a Z translation of 36.18 mm or 0.03618 to change the LiDAR range data to sensor X,Y,Z data. Does this mean that if I have a point with z=3 then after doing the translation it will be 3.03618?

Any help will be very appreciated.

Thanks
Ethan

**Comment by dgarbuzov** [comment]
The z translation from the user guide is the offset from the sensor mount to the origin in the lidar frame -- the coordinate frame in which lidar measurements are reported.

If you want z=0 to be roughly at ground level, yes you will have to take the height of your vehicle into account.
