### ISSUE TITLE
Sample lidar bag data V1.13 and V1.12

### ISSUE THREAD

**Issue by mrgransky** [ouster-lidar/ouster_example#141]
There are currently two sources to obtain some sample `file.bag` in ouster [website](http://data.ouster.io/sample-data-1.13/index.html) and ouster [github](http://data.ouster.io/sample-data-1.12/index.html) page.

However, the website [data.ouster.io](http://data.ouster.io/) seems to be broken and I have noticed there are more sample `file.bag` from ouster.

Does anyone know where exactly is a complete list of files to download?
For instance, I found [this](http://data.ouster.io/downloads/office_demo_9_25_19.bag) from this [github](https://github.com/wilselby/ouster_example/commit/9e6c0170b39015e8993b86f8146ba166e8e8cf4c).

Cheers,

**Comment by dgarbuzov** [comment]
The 1.12 and 1.13 sample data you linked is all we currently make widely available. We're working on a much more comprehensive public data set for the next release, stay tuned!
