### ISSUE TITLE
PTP Grandmaster Clock External Hardware

### ISSUE THREAD

**Issue by mrgransky** [ouster-lidar/ouster_example#143]
Suggested by Ouster SW guide, Trimble GM100 is used as an external PTP external grandmaster clock. It seems PTP Grandmaster Clock GM100 has come to an end of its ife product, according to [this](https://www.zti-communications.com/ptp-gm100/).

I was wondering if anyone knows a similar PTP grandmaster clock HW to buy which is most likely research affordable?

Cheers,

**Comment by daniel-dsouza** [comment]
If all you need is PTP time stamping, the cheapest solution is to use the hardware you already have - your computer via [ptp4l](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/deployment_guide/s1-using_ptp#s2-Checking_for_Driver_and_Hardware_Support)!

**Comment by mrgransky** [comment]
I need to synchronize my GPS receiver with my OS1.
Isn’t PTP grandmaster HW provides higher accuracy?

**Comment by Krishtof-Korda** [comment]
Hi, @mrgransky 

If you just need to sync GPS with OS1 you can do it via PPS and NMEA over UART, no GM needed. The accuracy will be very much the same as if you did it through PTP and would save you having to purchase an expensive GM.

Just follow the instructions in [How to Synchronize GPS with Ouster Sensor
](https://ouster.atlassian.net/servicedesk/customer/kb/view/988872783) 

Cheers!
