### ISSUE TITLE
Local Coordinate to Global Coordinate

### ISSUE THREAD

**Issue by ethan20120** [ouster-lidar/ouster_example#156]
Hi, 

Can anyone please suggest me which platform should I choose to change my local coordinate of the LiDAR(East, North, and UP) into global coordinate system (Latitude, Longitude, and Altitude)? I am trying to use the matlab (mapping toolbox) but it's taking very long time. 

Thanks

**Comment by aishanou-farmwise** [comment]
You can try https://geographiclib.sourceforge.io/ . It has different conversion methods in both cpp and python. I have only used the cpp methods though.
