### ISSUE TITLE
Coordinate transformation between (os1_lidar to os1_sensor)

### ISSUE THREAD

**Issue by ethan20120** [ouster-lidar/ouster_example#161]
Can anyone please guide me how can I do a (180 degree) rotation of the x,y,z points about the z axis?

Let's say I have x=1.019, y=-0.057, and z=-.105. If I rotate it into 180 degree angle about the z axis then what the coordinates will be ? 

Any help will be highly appreciated.

Thanks
Ethan

**Comment by dsb6063** [comment]
Quick rotation about the z-axis 180 degrees multiply by -1

matrix is something like below. values are in the 4th quadrant, rotation by 180 puts you in the 2nd quadrant.

R[x,y,z] = [cos(a) ,-sin(a), 0 ], [sin(a), cos(a), 0], [0,0,1] * [1.019,-0.057,-0.105] = [-1.019,0.057,-0.105]


________________________________
