### ISSUE TITLE
Possibly wrong transformation between IMU frame and sensor frame?

### ISSUE THREAD

**Issue by mcamurri** [ouster-lidar/ouster_example#168]
Hi all,
I work for the Oxford Robotics Institute at the University of Oxford. Congratulations for the quality of your devices, we use them on a variety of robots and we are very happy of their performance.

We have recently built a new handheld device composed of a RealSense D435i, a computer and an Ouster OS1. The device description is available [here](https://github.com/ori-drs/rooster_description/tree/kalibr-check). **Note that I made a [URDF of the Ouster](https://github.com/ori-drs/rooster_description/blob/kalibr-check/urdf/ouster.urdf.xacro) myself, which you are free to take and incorporate into your package**.

**My issue is the following:**
while calibrating the transformation between the camera optical frame and the IMU frame of the Ouster, our [calibration tool](https://github.com/ethz-asl/kalibr) consistently reported a different location of the IMU frame from what is published by the Ouster driver.

In particular, the following pictures show the nominal IMU frame (thin) and the IMU frame estimated by our camera-to-imu calibration tool (thick). The difference between the two frames is approximately `2.5 cm`.

![image](https://user-images.githubusercontent.com/13381545/83411229-b799dc00-a40f-11ea-97f6-8793102a1205.png)
![image](https://user-images.githubusercontent.com/13381545/83411299-df893f80-a40f-11ea-95aa-a41eeb7c4191.png)

Both camera and Ouster are rigidly attached to the device and their location is known from CAD, so it can't be off by more than a fraction of mm.

The device returns the following transform from `os1_sensor` to `os1_imu` (values are in `mm`):
```
{"imu_to_sensor_transform": [1, 0, 0, 6.253, 0, 1, 0, -11.775, 0, 0, 1, 7.645, 0, 0, 0, 1]}
```  
This is the same value you find in the manual, and it is what I've put in the URDF.

However, the calibration tools reports (in the same format as yours):
```
{"imu_to_sensor_transform": [1, 0, 0, -0.399, 0, 1, 0, 12.856, 0, 0, 1, 5.808, 0, 0, 0, 1]}
```

**Is it possible that the value reported by the Ouster driver is different from reality?**

If so, do you provide an official calibration tool to perform LIDAR to IMU calibration?

**Comment by dgarbuzov** [comment]
We haven't received any other reports of the imu location being inaccurate that I could find, and 2.5 cm seems much larger than what could be possible from a manufacturing defect (though that's just a hunch, I don't have any particular knowledge of the process).

Thanks for the detailed feedback. Closing this for now.
