### ISSUE TITLE
subscriber error

### ISSUE THREAD

**Issue by JackDevlin** [ouster-lidar/ouster_example#17]
Hello, Ouster team!
I am going to get cloud points from  os1 lidar camera.
So I am working now with bag files in  http://data.ouster.io/sample-data-2018-08-29/index.html .
In ubuntu my work is follow.
-To replay raw sensor output, run roslaunch ouster_ros os1.launch replay:=true
-In a second terminal, run rosbag play --clock <bagfile>
-To pulish on window 10, run rosrun rosserial_server socket_node points:=/os1_node/points
In window my work is follow.

#include "stdafx.h"
#include <string>
#include <stdio.h>
#include "ros.h"
#include "sensor_msgs/PointCloud2.h"
#include <windows.h>

using std::string;

void estimated_pose_callback( const sensor_msgs::PointCloud2 & pose )
{
//   printf( "Received pose %d, %d\n", pose.width,
// 		  pose.height);
	printf( "%f", 0.1f );
}
int _tmain( int argc, _TCHAR * argv[] )
{
  ros::NodeHandle nh;
  char *ros_master = "10.70.3.75:11411";
	
  printf( "Connecting to server at %s\n", ros_master );
nh.initNode( ros_master );

ros::Subscriber < sensor_msgs::PointCloud2>
poseSub( "points", &estimated_pose_callback );
nh.subscribe( poseSub );

printf( "Waiting to receive messages\n" );
while( 1 )
{
nh.spinOnce();
Sleep( 100 );
}

printf( "All done!\n" );
return 0;
}

But the callback funcion is not called.
What is my mistake?
If I use command roscore instead of roslaunch in Ubuntu, callback function calling is difference according to parameter.  

Thank you!

**Comment by dgarbuzov** [comment]
It looks like you're subscribing to "points" rather than "/os1_cloud_node/points". If you're working with our example code, try running `rostopic list` after connecting to the sensor to get a list of published topics.
