### ISSUE TITLE
Bug report with 1.14-beta10

### ISSUE THREAD

**Issue by TixiaoShan** [ouster-lidar/ouster_example#171]
I am using the 1.14-beta10 with OS1-128, I have observed the following two problems:

- "TIME_FROM_PTP_1588" timestamp_mode is not working. OS1-128 still reports timestamp from the internal OSC. The same configuration works with OS1-64-gen1 and v1.13.
- There is a "ring" in the center of the point cloud. The diameter is roughly 0.03m.

![snapshot1](https://user-images.githubusercontent.com/9648219/85140805-cce67700-b213-11ea-8049-feada77016e5.png)

**Comment by TixiaoShan** [comment]
"TIME_FROM_PTP_1588" mode seems to be working now. But it takes at least 2 minutes to sync.

**Comment by cynosure4sure** [comment]
I am  also having the same issue with a OS0-128 lidar. The lidar is on firmware 1.14.0-beta.12. The observation is the same that a ring appears in the 2-3cm range. One thing I noticed is that the pointcloud in ROS has no NaN or Zero points in it which is a bit odd that there are no invalid points in the cloud. Also the ring contains returns from multiple scanlines and not just a single one. Is it possible that invalid points are published on this ring?

![rviz_screenshot_2020_09_17-12_35_55](https://user-images.githubusercontent.com/7845970/93469089-47489500-f8f0-11ea-8344-ee9fabde71aa.png)

![rviz_screenshot_2020_09_17-12_36_59](https://user-images.githubusercontent.com/7845970/93469097-4adc1c00-f8f0-11ea-868e-707910d9ba09.png)

**Comment by dgarbuzov** [comment]
the ring issue should be fixed with #193. Please re-open otherwise
