### ISSUE TITLE
Security of ouster udp packets

### ISSUE THREAD

**Issue by madmax440** [ouster-lidar/ouster_example#173]
Hello Ouster Experts,

I am trying to understand the security mechanism employed with the UDP streams. I see that you have a UDP data stream pointed to a particular port and we provide you GNSS and PPS pulse input for timestamping / time adjustments.

It does seem to me that there is no security employed in establishing a connection (say DTLS) between the lidar sensor app processor and the receiving host connected over the ethernet. It does also seem that each packet never gets authenticated - to the least a HMAC.

This generally is risky as you know that the lidar receive stream "can be anyone" if the host processor listens in on the particular udp port mentioned in your manual. So could you please provide a response how this data channel can be secured ?

Thanks,
Dev

**Comment by dgarbuzov** [comment]
If you need to access sensor configuration and data over an unsecure network, you could use something like a VPN. Can't help beyond that -- if you need help with integration you can contact Ouster support and they might be able to put you in touch with one of our partners
