### ISSUE TITLE
os1-128-sample-data.bag. Needs code modifications to play

### ISSUE THREAD

**Issue by ChainBreak** [ouster-lidar/ouster_example#174]
I had to make the following code changes to play this ros bag [os1-128-sample-data.bag](https://ouster.ent.box.com/s/i9p4urir7ajr95oqzge2712smjv5ugte/file/635834626498)

### ouster_client/include/ouster/os1_packet.h: Line 16
```
// const int pixels_per_column = 64;
const int pixels_per_column = 128;
```

### ouster_client/src/os1_util.cpp: get_px_offset: Line 73
```
case 2048:
    // return repeat(16, {0, 12, 24, 36});
    return repeat(32, {0, 16, 32, 48});
```

**Comment by dgarbuzov** [comment]
gen2 / 128 support was added last week in #193
