### ISSUE TITLE
GPS Sync with Ouster Lidar OS1-32

### ISSUE THREAD

**Issue by adityarath302** [ouster-lidar/ouster_example#178]
Hello,
I have been working with Ouster 32 Channel Lidar for quite a sometime and I am stuck at a point where I need to sync a GPS Module with the Lidar. For a good SLAM, I brought a REACH M2 and now I have tried everything given in the software guide but still, I am not able to get the GPS to sync. I tried everything given on the Ouster Forum but still, the NMEA Locked variable is not turning to 1 as below. I think the issue is with the NMEA message received as this GPS supports GNRMC but ouster Supports GPRMC. Could anyone help me, please!!
PS: If PTP works where a Linux machine like raspberry pi is the master and GPS and Ouster act like a slave then please share the method with me.
Ref for GPS:https://forum.ouster.at/d/74-how-to-synchronize-gps-with-ouster-sensor
![image](https://user-images.githubusercontent.com/31166600/88211336-34f50680-cc73-11ea-8f3b-42a471affc3f.png)
This is what the sensor should return

Instead, it's giving me this
![image](https://user-images.githubusercontent.com/31166600/88211626-96b57080-cc73-11ea-9c1d-0d4d86edcf7d.png)
I am able to lock sync pulse in but nmea is not locking.

I am also not getting the time like this
![image](https://user-images.githubusercontent.com/31166600/88211867-edbb4580-cc73-11ea-822d-31e37ee17318.png)

where you can see the time in the first image.

**Comment by michielvlaminck** [comment]
I have the same problem. Were you able to solve it in the end?

**Comment by yulan0215** [comment]
> I have the same problem. Were you able to solve it in the end?

I had the same problem, did you solve it?

**Comment by michielvlaminck** [comment]
Yes, I believe the following TCP command did the trick:
`set_config_param nmea_ignore_valid_char 1`

Also make sure that the baud_rate of your GNSS matches the one of the Ouster scanner (and try both 9600 and 115200).

**Comment by yulan0215** [comment]
> Yes, I believe the following TCP command did the trick:
> `set_config_param nmea_ignore_valid_char 1`
> 
> Also make sure that the baud_rate of your GNSS matches the one of the Ouster scanner (and try both 9600 and 115200).

Thank you for your quick reply!
Do you mean input this  TCP command into the shell?

**Comment by michielvlaminck** [comment]
Yes, exactly.

You're welcome.

**Comment by yulan0215** [comment]
> Yes, exactly.
> 
> You're welcome.

Thx! I am sorry that is there any method to valid that the timestamp of Ouster LiDAR come from GPRMC? I will appreciate if you know it and tell me! Thx!

**Comment by michielvlaminck** [comment]
You can use Ouster Studio and check the timestamp there?

**Comment by yulan0215** [comment]
I used Ubuntu system.
Actually I would like to convert the format of the timestamp from Unix format into date to check if it is the time same as GMT. I used the Ouster driver for ROS system and I got the date by accident but when I would like to repeat it again, it did not work. I guess there was a command for the output of date. Like the picture I showed below:
![image](https://user-images.githubusercontent.com/62309959/111169340-26ad7f00-85a3-11eb-91f1-67f9e3c3ee46.png)

Do you know any command related to this? Thanks!

**Comment by AchmadFathoni** [comment]
Using firmware 2.3.5 on Rev-D lidar with `nmea_ignore_valid_char` set 1 still won't make Ouster decode GNRMC message. Ouster only able to lock and read the message. Here the attached json [time.json](https://github.com/ouster-lidar/ouster_example/files/14318819/time.json)

I know it is wrong place to complain about closed-source firmware but since the forum won't let me make new account because CAPTCHA, I have no other option.
