### ISSUE TITLE
Launch Error

### ISSUE THREAD

**Issue by yulan0215** [ouster-lidar/ouster_example#180]
After source I use the launch file of the ouster_ros, the problem is that I could not get access to the device:
REQUIRED process [os1_node-2] has died!
process has died [pid 19572, exit code 1, cmd /home/kws/catkin_ws/devel/lib/ouster_ros/os1_node __name:=os1_node __log:=/home/kws/.ros/log/2b2504ae-cf7d-11ea-8a5f-00044be66105/os1_node-2.log].
log file: /home/kws/.ros/log/2b2504ae-cf7d-11ea-8a5f-00044be66105/os1_node-2*.log
Initiating shutdown!
================================================================================
Can you give me some ideas about it? Thank you!

**Comment by dgarbuzov** [comment]
please verify that you've set up your connection to the sensor according to the Software User Manual. If you're still having issues that you suspect are due to a software problem, please re-open and include a full log of the commands you're running and the output.
