### ISSUE TITLE
[WARN]: Unknown sensor firmware version; output may not be reliable

### ISSUE THREAD

**Issue by SubMishMar** [ouster-lidar/ouster_example#181]
Hi,
I am trying to interface an Ouster (OS1) 128 channel lidar with ROS. I can ping the sensor and there is communication but I am not able to get any data from the sensor. 
Below you can see what messages I get on launching the os1.launch file. 
![Screenshot from 2020-08-03 17-01-38](https://user-images.githubusercontent.com/28704031/89231475-077d5680-d5ab-11ea-9ba3-988f955e3fc0.png)

When I echo the required topics I see no messages. Any idea what's wrong?

Thanks,
Subodh.

**Comment by adityarath302** [comment]
Try Changing the firmware on the device. Preferably v1.13.

**Comment by dllu** [comment]
**Please do not install firmware v1.13 on your OS1-128.** The GitHub code hasn't been updated to support the OS1-128 and other gen 2 sensors yet. Contact Ouster support for a link to the prerelease code that works with gen 2 devices.

**Comment by SubMishMar** [comment]
@dllu yes they have got back to me and I understand that the old stack wont work with gen2. So yes, I am not installing 1.13. Thanks for your response :)
