### ISSUE TITLE
The extrinsic between Ouster and its IMU

### ISSUE THREAD

**Issue by LeisureLei** [ouster-lidar/ouster_example#182]
Hi, I had a problem recently. According to the  OS1 software-user-guide-v1.13.0, I found OUSTER LIDAR frame is : x↓，y→，z↑，and sensor frame frame is: x↑,y ←,z↑. When I was using OS1-64, I found real LIDAR frame is: x↑,y ←,z↑, which is the same as sensor frame. Dose Ouster have done this transformation from LIDAR frame to sensor frame? What about IMU? How can I get the extrinsic between Ouster LIDAR and its IMU?
Looking forword to your reply!

**Comment by dgarbuzov** [comment]
[See section 3.1 in the Software User Manual](https://data.ouster.io/downloads/software-user-manual/software-user-manual-v2p0.pdf#8) for details about coordinate frames for sensor data.

This code will output lidar data in the sensor frame by default. This is done by querying the transform between the lidar and sensor frames from the sensor using the `get_lidar_intrinsics` TCP command. IMU data is reported in the IMU frame.

Not quite sure I understand your notation for the frames, but hope that clarifies it a bit.
