### ISSUE TITLE
[BUG] Pointcloud is flat, OS1-16

### ISSUE THREAD

**Issue by atyshka** [ouster-lidar/ouster_example#183]
Using an OS1-16, firmware 1.13, the pointlcloud output is flat along the z axis. This occurs both in rviz and the vtk viewer. Is this a 16 line specific issue? Our 64 line lidars work fine with this driver.

**Comment by atyshka** [comment]
Update: debugging the issue, it seems that the beam angles reported in the sensor config are zeroed out which would explain my error. Why would this be?

**Comment by dllu** [comment]
That seems to be a problem with the sensor rather than with the driver. Please contact Ouster support.

**Comment by atyshka** [comment]
Yeah, defective sensor, getting an RMA
