### ISSUE TITLE
Timestamp of each point in the point cloud

### ISSUE THREAD

**Issue by SubMishMar** [ouster-lidar/ouster_example#184]
I want to get the time stamped associated with each point in the point-cloud published on the topic `/os_cloud_node/points` .

The `header.stamp` field gives a time stamp.

And each point `p` has a field `t` which gives a time stamp that varies between 0 to a number which depends on data rate. From what I understand it just gives the time stamp of a point wrt the first point in a 360deg scan.

Is it correct to say that the time stamp of a point `p` in the scan wrt to the wall-time (inside the sensor or on the computer if ptp synced) = `scan.header.stamp` + `p.t`

Obviously, the assumption here is the scan time stamp is the time associated with the first point in the scan and not the last point in the scan.

**Comment by SubMishMar** [comment]
I realized now that the time field of a point equals `ts-scan_ts`. I will be glad to know why is it so? Why is it not just `ts`?

**Comment by dllu** [comment]
It was set to be ts - scan_ts because 

* absolute timestamps in IEEE 1588 PTP time sync mode or GPRMC/PPS time sync mode are UNIX timestamps that may overflow the 32 bit integer
* it maintains compatibility with some 3rd party packages such as LOAM-type slam algorithms that "dewarp" or "deskew" the point cloud based on the time since the start of the scan

**Comment by SubMishMar** [comment]
Thanks! @dllu

**Comment by BritskNguyen** [comment]
> I realized now that the time field of a point equals `ts-scan_ts`. I will be glad to know why is it so? Why is it not just `ts`?

Hi,

May I ask where found this definition, and what **ts** and **scan_ts** actually means with respect to the original defintions (**header.stamp** and **p.t**)?

Thanks

**Comment by gogojjh** [comment]
> I find this sentence in https://github.com/ouster-lidar/ouster_example/blob/13ea8e8b8a4951fb630dbc9108666995c8443bf6/ouster_ros/src/ros.cpp?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L126

**Comment by Alex-Beh** [comment]
@gogojjh @brytsknguyen Would you all mind to elaborate the meaning behind `ls.header(v).timestamp` and `scan_ts`? I suspect `scan_ts` is the timestamp of the first firing in current cycle.

**Comment by themightyoarfish** [comment]
It looks like `const auto ts = (ls.header(v).timestamp - scan_ts).count(); ` is actually the relative time difference, i.e. the first point would have ts = 0.
