### ISSUE TITLE
OS1-64 restarts or pauses when os1.launch called

### ISSUE THREAD

**Issue by GrantZheng86** [ouster-lidar/ouster_example#187]
I noticed that whenever I call the "os1.launch", the flashing red light in the LIDAR seemed to be turned off. It will turn back on after about 10 seconds. I am running ubuntu 18, with the most recent "ouster_example" files from this repo. There is a computer in my lab that is running ubuntu 16 with a much older version of the files from "ouster_example" (should be around 9 months to 1 year ago), and there was no restarting or pausing for the lidar. This restart or delay is actually causing problems in one of my big launch files, and it's throwing out errors `[FATAL] [1601500521.299787039]: F0930 15:15:21.000000 18745 ordered_multi_queue.cc:112] Check failed: last_dispatched_time_ <= next_data->GetTime() (621355973168931677 vs. 621355968400000656) Non-sorted data added to queue: '(2, /points2)'` And adding a delay between the "os1.launch" and another starting of a node will solve this issue. I am wondering what function is likely to cause this restart or delay? From the terminal output, it looks like rewriting of the metadata is likely to cause the problem, but I am not sure. Does anyone have any ideas about this?
 
Thanks for helping out!

Also, the code below is from the old os1.launch, which has no problem in resetting the lidar.

![os1 launch](https://user-images.githubusercontent.com/33077268/94836515-4f183700-03d0-11eb-86ff-8305fdb8eaf3.png)
![terminal_output](https://user-images.githubusercontent.com/33077268/94838082-4d4f7300-03d2-11eb-9d80-9c9c4dd06be8.png)

**Comment by dgarbuzov** [comment]
The provided launch file and ROS code will unconditionally re-initialize the sensor on startup, after updating the configuration parameters. Iirc, this has always been the case, so I can't explain why it might have worked with an old version.

If you want to avoid any gaps in the udp data stream on startup, you can modify the os_cloud_node to use the second overload of `init_client`:
https://github.com/ouster-lidar/ouster_example/blob/9352730127c3e2bc8ce1e778be4ae8b0a3b40f3c/ouster_client/include/ouster/client.h#L38

This will avoid reinitializing the sensor, but can't be used to update the configuration -- you'll have to e.g. set the lidar_mode separately.

**Comment by GrantZheng86** [comment]
Thanks for the advice, I'll Give it a try!
