### ISSUE TITLE
timestamp_mode Problem

### ISSUE THREAD

**Issue by salokin1997** [ouster-lidar/ouster_example#188]
Hello,
I have the following problem: I tried to launch the file `os1.launch` with 
```
roslaunch ouster_ros os1.launch lidar_mode:=512x10 timestamp_mode:=TIME_FROM_PTP_1588 os1_hostname:=10.0.0.11 os1_udp_dest:=10.0.0.10. 
```
I want to publish ros messages with the current unix time. But the timestamps still show the sim time. 
Thanks!

**Comment by dgarbuzov** [comment]
The provided ROS code just passes hardware timestamps through to messages when connecting to a live sensor, it does not use simulated or host system time. Please refer to the Software User Manual for setting up ptp and other options for setting up time synchronization:

https://data.ouster.io/downloads/software-user-manual/software-user-manual-v2p0.pdf#52
