### ISSUE TITLE
OS0-128 support?

### ISSUE THREAD

**Issue by boilerbots** [ouster-lidar/ouster_example#189]
Just got an OS0-128 and I can't get it running. Is it even supported yet?

**Comment by k-mohit** [comment]
Hi @boilerbots 
Did you operate the sensor with the latest firmware? If not please download the beta firmware for Gen 2 sensors [here](https://go.ouster.io/beta-program/beta-12/)

Hope this helps!

**Comment by boilerbots** [comment]
Yes this is the problem, my Lidar came with the new firmware.
