### ISSUE TITLE
Wrong indexing in Image publish node 

### ISSUE THREAD

**Issue by MLEEKIMM** [ouster-lidar/ouster_example#190]
in "img_node.cpp",
const size_t vv = (v + px_offset[u]) % W; 
"px_offset" variable provides offset....  
However, the code is subscribing the pcl message, not a packet data of Ouster lidar.  so the line should be
const size_t vv = (v + ((u)%2)*8 ) % W;   
then, the output image is getting more fit. 
My question is why the offset value is 8 and only works for the odd number lines. May be it is related with the pcl_cloud library....

**Comment by dgarbuzov** [comment]
The structured point cloud published by the `os_cloud_node` matches the layout of points in "staggered" output, so using the px_offset to reconstruct the image is still appropriate. I can't reproduce any issues with staggering in the image node output, but please reopen with some screenshots if you're still having this issue.
