### ISSUE TITLE
How to persist the changes for PTP synchronization with LinuxPTP Grandmaster and usage or importance of chrony?

### ISSUE THREAD

**Issue by afridi26** [ouster-lidar/ouster_example#197]
Hey everyone,

**I know the time is not correct as you can see in the screenshot, even if I set the time correctly the problem is same.**

I follow the [official](https://data.ouster.io/downloads/software-user-manual/software-user-manual-v2p0.pdf#52) documentation to setup PTP for the Os1-64 (GEN 1) till the end of section 15.6.3 (Configuring phc2sys to Synchronize the System Time to the PTP Clock) and everything is working fine.

However,  when the system is rebooted or shutdown and started again, I get the following output for the commands (_I did debugging to find the root cause of the problem_):

![error1](https://user-images.githubusercontent.com/5488091/102077976-22bd6580-3dd8-11eb-9f3d-b84aacd2d843.png)
similarly,
![error2](https://user-images.githubusercontent.com/5488091/102078007-31a41800-3dd8-11eb-9f28-9bb1eccf981e.png)
and 
![error3](https://user-images.githubusercontent.com/5488091/102078018-3a94e980-3dd8-11eb-918e-1a8aee0aa1e5.png)
However, When I reload the daemon, it starts working again:
![error4](https://user-images.githubusercontent.com/5488091/102078114-5d270280-3dd8-11eb-9582-61e892b0cafd.png)

So there are now two questions,
1) How to persist the changes, so when I restart the system, the ptp4l should be working such I should not run the 
`sudo systemcl daemon-reload `or `sudo systemctl restart phc2sys` on every restart.

2) What is chrony? Which is mentioned in official documentation? Should I need to configure it also because I skipped this section (15.6.4 Configuring Chrony to Set System Clock Using PTP) for ptp4l setup.

Any help would be appreciated :)

Thanks.

**Comment by afridi26** [comment]
Fixed typo

**Comment by afridi26** [comment]
Nevertheless, I solved the problem by enabling the service as follows (I forget to enable the ph2sys service):

`sudo systemctl enable phc2sys.service`

and the run

`sudo systemctl daemon-reload`

Thanks

**Comment by afridi26** [comment]
Hey,

the problem still persist? Can anyone guide how this can be fixed?

Regards,
Aftab

**Comment by dgarbuzov** [comment]
That warning about `systemctl daemon-reload`being needed only happens when the service files are modified. If that always happens on boot, something may be mis-configured on your system and overwriting those files. Could double-check the mtime to make sure.
