### ISSUE TITLE
Ring Index in ROS driver (using matlab)

### ISSUE THREAD

**Issue by AndreasInSchwaben** [ouster-lidar/ouster_example#198]
Hi,

if the ROS driver's topic would include a ring index, more advanced post-processing would be possible. The ring-index allows to identify each Lidar point to the transmitted beam. 
See e.g.: https://answers.ros.org/question/132811/accessing-layers-in-velodyne-point-cloud/  

would be great to have this feature available!
Thanks a lot!
Andreas

**Comment by dgarbuzov** [comment]
If I understand the question, it's there already:
https://github.com/ouster-lidar/ouster_example/blob/5c00aa97ee8244072ed9bf14870facf57d4aab98/ouster_ros/include/ouster_ros/point.h#L23
I'm able to select `ring` as a channel in rviz and visualize it, etc.

**Comment by AndreasInSchwaben** [comment]
Dear all,

agreed!
The feature of the ring-number already exists in rosbags and RVIZ is able to display or visualize them.

However, in all the documentation  available to us, we have not found any hint on that feature.
Would you mind to update the documentation with the ring-numbers, please?

Thanks a lot & Merry Christmas
Andreas

**Comment by AndreasInSchwaben** [comment]
Dear Ouster,

we are still waiting for an API documentation, how the Ring index may be read from Lidar data, your ROS driver or topic.

Best Regards
Andreas Schwager

**Comment by dgarbuzov** [comment]
We'll be updating and publishing API docs for the sample code as our schedule allows. Until then, if I'm happy to answer any specific questions you might have.

**Comment by AndreasInSchwaben** [comment]
Dear Ouster Colleagues,

we are searching for an API definition how data are sorted in the ROS topic sent by your ROS-driver.
We are reading the ROS topic from Matlab where we do not have the support of e.g. RVIZ plugin.

Could you please send us any documentation how to read and interpret the ROS-topics send by Ouster ROS driver.

Thank you very much
Andreas


From: Schwager, Andreas <Andreas.Schwager@sony.com>
Sent: Freitag, 8. Januar 2021 09:50
To: ouster-lidar/ouster_example <reply@reply.github.com>; ouster-lidar/ouster_example <ouster_example@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [ouster-lidar/ouster_example] Ring Index in ROS driver (#198)

Dear Ouster,

we are still waiting for an API documentation, how the Ring index may be read from Lidar data, your ROS driver or topic.

Best Regards
Andreas Schwager

**Comment by dgarbuzov** [comment]
Unfortunately we don't currently provide support for matlab in this repo. I'll reopen this issue in case other users that have some more experience reading ROS topics in matlab can share their solutions.

If I understand correctly, you're able to receive point clouds, but are having trouble getting the actual field data. Have you tried the [readField() function](https://www.mathworks.com/help/ros/ref/readfield.html)? It looks like it should allow you to read the additional fields defined for [our point type](https://github.com/ouster-lidar/ouster_example/blob/master/ouster_ros/include/ouster_ros/point.h) like "ring". [This function to enumerate all available fields in a point cloud](https://www.mathworks.com/help/ros/ref/readallfieldnames.html) might also be useful.
