### ISSUE TITLE
Running 2 OS-1 Lidars

### ISSUE THREAD

**Issue by Saumya-Shah** [ouster-lidar/ouster_example#199]
Hi, I am trying to run 2 OS-1 lidars on ROS. I am using a router which is connected to the 2 lidars via ethernet and to the desktop via wifi connection. 

These are eventually the 3 devices on the network.
![Screenshot from 2020-12-22 16-52-08](https://user-images.githubusercontent.com/22060625/102936379-112e2a80-4476-11eb-9164-29811c3c6403.png) 

The following is the launch file I had prepared:

[ouster2lidar.launch](https://github.com/ouster-lidar/ouster_example/files/5732172/ouster2lidar.txt)

And this is the command I run it with:

`roslaunch ouster_ros ouster2lidar.launch sensor_hostname_0:=os1-992006000706.local sensor_hostname_1:=os1-991933000275.local udp_dest:=192.168.1.7 lidar_mode:=2048x10 viz:=false 
`

I do not get a stable frequency of output while operating at the above lidar_mode. I tried at 512x20 and it was quite stable to maintain at 19-20, but at 2048x10, there is sometimes no message and there is 5hz frequency otherwise. 

Did I do something wrong or is there a better way to do it?

Thanks,
Saumya

**Comment by dgarbuzov** [comment]
It looks like your host machine is connected via (2.4 ghz!) wifi. This will almost certainly not keep up with the amount of UDP traffic generated by two OS-1s. We recommend a gigabit ethernet connection for reading lidar data.
