### ISSUE TITLE
Point cloud registration

### ISSUE THREAD

**Issue by dcazzato** [ouster-lidar/ouster_example#20]
Dear all,

I would like to ask you if you are planning to release (and in positive case, when) any code about point cloud registration, like in your demo videos at your website.

Best regards,

**Comment by dgarbuzov** [comment]
We don't have any plans to release that code, but some of our users have had success adapting existing SLAM implementations to work with the OS-1.

We're definitely interested in making it easy to get started mapping with the OS-1 and welcome any contributions to the sample code.
