### ISSUE TITLE
OS1 lidar beam configurations

### ISSUE THREAD

**Issue by jonra1993** [ouster-lidar/ouster_example#202]
Hello, Oustear team I am currently working on using OS1-32 LiDAR using ROS. I was looking at the documentation and ROS node but there is nothing related to beam configuration from Uniform, Gradient, and Below Horizon. First I would like to know how to check that using API and if it is possible to change config using ROS. Please let me know if it is possible to do that.

![image](https://user-images.githubusercontent.com/23468720/103576771-a7644680-4ea1-11eb-8bb5-fd3bb2a50880.png)

**Comment by dllu** [comment]
There is no way to change that on the fly. Once you buy the sensor, it is fixed.
