### ISSUE TITLE
How to verify the performance of synchronized LiDAR and IMU data ?

### ISSUE THREAD

**Issue by ajay1606** [ouster-lidar/ouster_example#203]
Hello,
I am currently using Ouster 16 channel (os-1) model lidar and am testing PTP synchronization method. I follow the instruction manual provided by Ouster. But I want to verify the is a performance by estimating delay if here. So how I can verify, could any please suggest.

Thanks in advance.

**Comment by dgarbuzov** [comment]
The ["Verifying PTP operation" section of the user manual:](https://data.ouster.io/downloads/software-user-manual/software-user-manual-v2p0.pdf#60) may be what you're looking for.
