### ISSUE TITLE
ROS2 compatibility?

### ISSUE THREAD

**Issue by HappySamuel** [ouster-lidar/ouster_example#205]
Hi

Recently, a lot of people has moved into the ROS2, as well as industrial side. Is there any ouster_ros on ROS2 ?

Best,
Samuel

**Comment by dgarbuzov** [comment]
There's a ROS2 driver available in the official ROS repos: https://github.com/ros-drivers/ros2_ouster_drivers

Gen2 / firmware 2.0 is not currently supported, however.

**Comment by RFRIEDM-Trimble** [comment]
For anyone reading this, the ROS2 driver linked above now supports Gen2 / firmware 2.0.
