### ISSUE TITLE
Request: Publish Images of Ambient, Intensity, Range data in ouster_ros

### ISSUE THREAD

**Issue by eric-schleicher** [ouster-lidar/ouster_example#21]
In the most recent update the new Viz tool renders Ambient, Intensity and Range above each cloud.

It would be very beneficial to for the ros integration to also include/publish these data types.  They are really useful and many applications prefer to consume/transport data in these formats.

**Comment by dgarbuzov** [comment]
The latest update includes code that publishes each channel as ROS image topics. See the readme under ouster_ros/.

**Comment by ShreyasSkandan** [comment]
This works great, thanks.

**Comment by eric-schleicher** [comment]
Thanks You! this is truly excellent.
