### ISSUE TITLE
Help with sparse point cloud captured by Ouster OS1-64

### ISSUE THREAD

**Issue by xavidzo** [ouster-lidar/ouster_example#221]
Hi, I am using for my project the OS1-64 sensor (the model with laser beam below the horizon) to scan and detect vehicles on the highway. I mounted the sensor in a static position on top of a bridge. The captured point clouds seem to be rather sparse, especially there is a very low amount of points being reflected from the ground and cars, only trucks and middle-size vehicles have a decent amount of points. Also, I checked the pcd files and only half of the points had usable values, the other half were only filled with zeros.
Please see the image below to better understand my issue, (pcd files displayed with the PCL library)
![ouster_OS1-64](https://user-images.githubusercontent.com/8997312/106882445-0aced780-66df-11eb-85cc-431c6466ff96.gif)

Here is an example of another recording I did on the same highway with the Velodyne VLS-128 sensor:
![velodyne_VL128](https://user-images.githubusercontent.com/8997312/106889197-f7743a00-66e7-11eb-8086-566fdc975fd2.gif)

As you can see the Velodyne sensor captures a very dense point cloud from the environment. This is reasonable because it has more channels than Ouster (128 vs 64), more range, and its price is also much higher, so that should play an important role as well. Nevertheless, that does not explain why the ground is low reflective in the ouster recording, and why the point cloud is quite sparse even in the near range. Could you give me please some recommendations about the settings for my case scenario (lidar sensor mounted statically on top of the highway)? Maybe I am using a not so convenient configuration...

**Comment by kwong0** [comment]
Hi @xavidzo,

This is likely a sensor hardware issue. For customer support, please contact [Ouster customer support](https://ouster.atlassian.net/servicedesk/customer/portal/8/group/22/create/86). If you could mention this ticket and link it in your support ticket, that would be really helpful.

Thanks!
