### ISSUE TITLE
Please remove the note from the Windows install instructions on the Readme

### ISSUE THREAD

**Issue by jcheungEncompass** [ouster-lidar/ouster_example#226]
Hi, 

I recently went through the install and setup instructions to set up the sample client and visualizer and found that the following note caused errors:

>  Note You'll need to run git checkout 2020.07 in the vcpkg directory before bootstrapping to use the correct versions of the dependencies. Building may fail unexpectedly if you skip this step.

I ended up returning back to the master branch and from there the install worked fine.

**Comment by kairenw** [comment]
Thanks for pointing this out, @jcheungEncompass. We've touched up the README w.r.t building on Windows.
