### ISSUE TITLE
Multiple instances of the phc2sys service

### ISSUE THREAD

**Issue by afridi26** [ouster-lidar/ouster_example#229]
Hey,

I am trying to setup a boundary clock. I own a device with multiple ports. The device is connected to GPS via USB and time is synchronized using chrony. I have two sensors, an industrial camera and  ouster lidar. These sensors are directly connected and I want the Ubuntu OS to be master and all other slaves. The industrial camera has the 10.1.1.1 network while the ouster lidar is connected to the system via a link local IPv4.
I made the following entries in the `/etc/linuxptp/ptp4l.conf`

```
boundary_clock_jbod 1
[enp7s0]
[enp8s0]
```
While I was setting up the PTP, I got confused and  didn't know what to do further. On Page 90 of the[ Ouster official user manual](https://data.ouster.io/downloads/software-user-manual/software-user-manual-v2p0.pdf), there is note about phc2sys which is:

`Note: If multiple interfaces need to be synchronized from CLOCK_REALTIME then multipe instances of
the phc2sys service need to be run as it only accepts a single slave (i.e. -c) argument.` 

Can anyone guide me how to set up the phc2sys for multiple interfaces or is there a need for phc2sys. I have two ports on which the slaves are connected directly while Ubuntu is master.

P.s By the way there is a typo on the same note in the user manual: it should be multiple not multipe. 

Regards,
Affi

**Comment by dgarbuzov** [comment]
Haven't done this in a while, but iirc phc2sys has an "autoconfigure" flag which queries the interfaces from the ptp4l daemon and may be what you're looking for. Might be worth trying: `sudo phc2sys -a -rr -m` in a terminal while ptp4l is running.
