### ISSUE TITLE
Issue of timestamp of Ouster LiDAR

### ISSUE THREAD

**Issue by yulan0215** [ouster-lidar/ouster_example#231]
Hi:
I have a question that I followed the instruction in the weblink: https://forum.ouster.at/d/74-how-to-synchronize-gps-with-ouster-sensor
And I checked the synchronization by TCP. However, when I ran the driver of Ouster LiDAR, the LiDAR was still used the time from the Ubuntu system. Can you give me some ideas how to solve this problem? Thx!

**Comment by yulan0215** [comment]
> Hi:
> I have a question that I followed the instruction in the weblink: https://forum.ouster.at/d/74-how-to-synchronize-gps-with-ouster-sensor
> And I checked the synchronization by TCP. However, when I ran the driver of Ouster LiDAR, the LiDAR was still used the time from the Ubuntu system. Can you give me some ideas how to solve this problem? Thx!

And I would like to add one more information that my GPS module not only give the message "GPRMC". It also transfer other messages(for instance: GPGGA). I would like to ask is it influence the timestamp of my lidar? The timestamp was still the ROS time. Thanks!

**Comment by yulan0215** [comment]
> > Hi:
> > I have a question that I followed the instruction in the weblink: https://forum.ouster.at/d/74-how-to-synchronize-gps-with-ouster-sensor
> > And I checked the synchronization by TCP. However, when I ran the driver of Ouster LiDAR, the LiDAR was still used the time from the Ubuntu system. Can you give me some ideas how to solve this problem? Thx!
> 
> And I would like to add one more information that my GPS module not only give the message "GPRMC". It also transfer other messages(for instance: GPGGA). I would like to ask is it influence the timestamp of my lidar? The timestamp was still the ROS time. Thanks!

I think I solved the problem but one another problem is what command can I input to get the date (in the terminal). Shown below:
![image](https://user-images.githubusercontent.com/62309959/111079522-9fa4cc00-84fa-11eb-9e3f-1052805459a9.png)

Thx!

**Comment by Krishtof-Korda** [comment]
> I think I solved the problem but one another problem is what command can I input to get the date (in the terminal). Shown below:
> ![image](https://user-images.githubusercontent.com/62309959/111079522-9fa4cc00-84fa-11eb-9e3f-1052805459a9.png)
> 
> Thx!

@yulan0215 can you clarify the question? Are you looking for a command to the sensor or a terminal command? Can you explain exactly what you are trying to achieve? Thanks.

**Comment by dgarbuzov** [comment]
Haven't gotten a response; please reopen if you're still having issues

**Comment by yulan0215** [comment]
> Haven't gotten a response; please reopen if you're still having issues

I am sorry I still have problem.

**Comment by dgarbuzov** [comment]
Are you able to get in touch with Ouster support? That would be a better channel for this question

**Comment by yulan0215** [comment]
> Are you able to get in touch with Ouster support? That would be a better channel for this question

Thx! I will contact them later.
