### ISSUE TITLE
Range map in ROS image node

### ISSUE THREAD

**Issue by theNded** [ouster-lidar/ouster_example#234]
The point's property is defined as 
https://github.com/ouster-lidar/ouster_example/blob/master/ouster_ros/include/ouster_ros/point.h#L25, 
with `range` as the 7-th property. However, in function `scan_to_cloud`, this field is filled with `REFLECTIVITY`:
https://github.com/ouster-lidar/ouster_example/blob/master/ouster_ros/src/ros.cpp#L86

Could this be a bug, or is there any other specific reason for this implementation? Seems PR #220 is addressing this.
Thanks!

**Comment by MaxandreOgeret** [comment]
Definitely a bug @dgarbuzov

**Comment by kairenw** [comment]
Thanks for catching this, @theNded! We've fixed this in the [latest master](https://github.com/ouster-lidar/ouster_example/blob/master/ouster_ros/src/ros.cpp#L86), so I'm closing this issue now.
