### ISSUE TITLE
black strip on Ouster lidar

### ISSUE THREAD

**Issue by ge25nab** [ouster-lidar/ouster_example#235]
![image](https://user-images.githubusercontent.com/45938420/113344146-fdc21380-9330-11eb-82a5-710b2cb08065.png)
![image](https://user-images.githubusercontent.com/45938420/113344187-061a4e80-9331-11eb-8355-f696b79f9c17.png)

I'm facing the black strips problem on ouster lidar, as shown in the first figure.  But it is ought to be the form in the second figure, where no black strips inside.
If someone faced similar problems or have some ideas about how to solve it, please leave messages here.

**Comment by rcabg** [comment]
hey @ge25nab , did you compile using RELEASE mode?

catkin_make -DCMAKE_BUILD_TYPE=Release

**Comment by kairenw** [comment]
Hi @ge25nab, if this is still an issue, I'd encourage you to [contact Ouster support ](https://ouster.atlassian.net/servicedesk/customer/portal/8/group/22/create/86). Closing this issues now.
