### ISSUE TITLE
os1_node crashes on ARM processor

### ISSUE THREAD

**Issue by ilia-sheremet** [ouster-lidar/ouster_example#24]
Hello Ouster team!

I encountered an issues with Eigen library while trying to run **os1_node** on Odroid-UX4 with ARM processor architecture. I compiled and run it previously on x86 without any problems.

Output of **uname -a**:
`Linux odroid 4.14.5-92 #1 SMP PREEMPT Mon Dec 11 15:48:15 UTC 2017 armv7l armv7l armv7l GNU/Linux`

Here is the output of **catkin_make**: https://pastebin.com/ykjSqS4r

Here is the error while running of the command **roslaunch ouster_ros os1.launch replay:=true** :
>os1_node: /usr/include/eigen3/Eigen/src/Core/DenseStorage.h:109: Eigen::internal::plain_array<T, Size, MatrixOrArrayOptions, 16>::plain_array() [with T = float; int Size = 4; int MatrixOrArrayOptions = 0]: Assertion `(reinterpret_cast<size_t>(eigen_unaligned_array_assert_workaround_gcc47(array)) & (15)) == 0 && "this assertion is explained here: " "http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html" " **** READ THIS WEB PAGE !!! ****"' failed.
Aborted

The error happens during initialization of `struct EIGEN_ALIGN16 PointOS1`. Moreover it doesn't appear every run, but 9/10 times. I followed the [link](http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html) above and tried to patch it using tips provided there, but non of my solutions helped.

Here is the output of Valgrind debugger **valgrind --track-origins=yes  ./devel/lib/ouster_ros/os1_node replay:=true** :  https://pastebin.com/jtzL77aF

Does anyone have similar issues?

**Comment by dsb6063** [comment]
I had several issues with the Eigen libraries. You may want to try the newest version of ROS. If that does not work, you may need to rollback the current eigen libs and install the standalone eigen 3 libs. However, this usually leds to other issues to figure out.

**Comment by dgarbuzov** [comment]
Building on ARM seemed to work for me -- could you try the latest update and reopen the issue if this is still a problem?

**Comment by ilia-sheremet** [comment]
@dgarbuzov Building was never a problem for me, please check the initial post. 
The problem appears when you run the **OS_1** node. And the problem appears around 4/5 times, so eventually, it works.
Please let me know if you need more logs
