### ISSUE TITLE
error while building

### ISSUE THREAD

**Issue by Karthikeyanc2** [ouster-lidar/ouster_example#243]
Hello,

I am not able to sucessfully build the project. 
I have attached the snip from terminal

![ouster_example_install](https://user-images.githubusercontent.com/53954194/117827515-57dbc000-b271-11eb-8c32-a3b3ab31a8b1.png)

**Comment by sidml** [comment]
I got the same error.
One possible fix is to change `auto n_invalid` to `size_t n_invalid` [here](https://github.com/ouster-lidar/ouster_example/blob/e1176f427f68eb0807bb15ccabe34aea47a1c5d3/ouster_client/src/example.cpp#L114)

**Comment by Karthikeyanc2** [comment]
Thank you very much...It worked!!
