### ISSUE TITLE
ValueError: Unexpected number of beam_altitude_angles

### ISSUE THREAD

**Issue by x86-64-slc6-gcc47-opt** [ouster-lidar/ouster_example#248]
Hi, I try to read OS (16 channels) datafile via Python using sdk example pcap and get next error:

WARNING: No data_format found
ValueError: Unexpected number of beam_altitude_angles

Can I fix it or I need to read it by other way ?

**Comment by dgarbuzov** [comment]
what's the source of the pcap and metadata json file?

**Comment by x86-64-slc6-gcc47-opt** [comment]
> what's the source of the pcap and metadata json file?

I was recording data through the Ouster Studio 3.6.0-777 latest from here: https://www.paraview.org/ousterstudio/

**Comment by dgarbuzov** [comment]
Looks like that's an old version of ouster-studio (notice the 2019 timestamp in the executable) that doesn't record all the necessary metadata for FW 2.0+. An up-to-date one is available from the downloads page on the ouster downloads page: https://ouster.com/downloads/

What firmware version are you running? Were you able to visualize sensor output in that old version of Ouster Studio?

Thanks for pointing this out -- maybe we can provide a better error message here.

**Comment by x86-64-slc6-gcc47-opt** [comment]
> Looks like that's an old version of ouster-studio (notice the 2019 timestamp in the executable) that doesn't record all the necessary metadata for FW 2.0+. An up-to-date one is available from the downloads page on the ouster downloads page: https://ouster.com/downloads/
> 
> What firmware version are you running? Were you able to visualize sensor output in that old version of Ouster Studio?
> 
> Thanks for pointing this out -- maybe we can provide a better error message here.

I upgraded lidar to version -- ousteros-image-prod-aries-v2.0.0+20201124065024. Yes I can visualize sensor output in that old version. I checked packet size and I get 10 packet per frame each packet 3434 bytes ( Should I got 3392 bytes? ).  
I think that i can get data from packets if i find packet data format. Could you help me with this ?

**Comment by dgarbuzov** [comment]
Not quite sure I follow -- I was saying you should download a newer version of Ouster Studio and re-record your data (but updating FW is a good idea as well).

**Comment by dgarbuzov** [comment]
Haven't gotten a response; closing for now. Please reopen if you're still having issues.
