### ISSUE TITLE
publish ROS timestamp with eno device

### ISSUE THREAD

**Issue by snakehaihai** [ouster-lidar/ouster_example#25]
@rafficm 
I`ve been following this https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/deployment_guide/s1-using_the_ptp_management_client 
to sync 
but both of my PC doesn't support it by having eno device.
Any good solution(besides ask me to buy another PC) ?

Command: ethtool -T eno1  
Time stamping parameters for eno1:
Capabilities:
	software-transmit     (SOF_TIMESTAMPING_TX_SOFTWARE)
	software-receive      (SOF_TIMESTAMPING_RX_SOFTWARE)
	software-system-clock (SOF_TIMESTAMPING_SOFTWARE)
PTP Hardware Clock: none
Hardware Transmit Timestamp Modes: none
Hardware Receive Filter Modes: none
Command: ptp4l -i eno1 -m
Result:
interface 'eno1' does not support requested timestamping mode.

I tried another ethernet to USB adapter. Result is the same
Command:  ptp4l -i enx00051bd3111d -m
Result:
interface 'enx00051bd3111d' does not support requested timestamping mode.
sna

**Comment by snakehaihai** [comment]
emm for now. I subscribed to a high-frequency IMU and couple the LIDAR reading to most closest IMU reading. W8ing for your guys to come up with better solution

**Comment by snakehaihai** [comment]
Emm I cant. after subscribing to LIDAR and added correct time stamp and then publish. takes too much CPU which cause the CPU to overload. Do you guys have any good suggestion?

**Comment by dgarbuzov** [comment]
Besides PTP, you can also use a PPS signal to synchronize with external hardware. Please check your OS-1 manual for time synchronization options.

**Comment by mrgransky** [comment]
@dgarbuzov do we need to open interface box to synchronize GNSS receiver with OS1?
   ```
GNSS          -->       OS1-64
   NMEA_Transmit --> multipurpose_io_mode
   PPS           --> SYNC_PULSE_IN
   PPS_GND       --> GND
```
If so does it terminate the warranty?

**Comment by snakehaihai** [comment]
> @dgarbuzov do we need to open interface box to synchronize GNSS receiver with OS1?
> 
> ```
> GNSS          -->       OS1-64
> NMEA_Transmit --> multipurpose_io_mode
> PPS           --> SYNC_PULSE_IN
> PPS_GND       --> GND
> ```
> 
> If so does it terminate the warranty?

its ok. we break all our box :) you have to break it. and cut the cable if possible. the cable too long
