### ISSUE TITLE
Is there a way to tell if a lidar beam has no return?

### ISSUE THREAD

**Issue by versatran01** [ouster-lidar/ouster_example#250]
For example, in an open space where everything is very far away, what would the range value be in the packet?

**Comment by versatran01** [comment]
Related ROS REP
https://www.ros.org/reps/rep-0117.html

**Comment by dgarbuzov** [comment]
Currently Ouster sensors output (and the sample code here passes through) a zero range when there's no return.

Thanks for linking the REP, hadn't seen that before. Do you have an example of a lidar or rgbd camera driver that follows this spec for PointCloud2 topics? It's not currently possible to distinguish the "too close" vs "out of range" cases so it's not obvious how we'd implement this, but maybe there's an opportunity to do something more standard.

**Comment by versatran01** [comment]
Thanks for the reply. So for gen 2 sensor, 0 means "out of range", anything >0 should be treated as a hit, is this correct?

**Comment by i-sheremet** [comment]
> It's not currently possible to distinguish the "too close" vs "out of range" cases so it's not obvious how we'd implement this, but maybe there's an opportunity to do something more standard.

@dgarbuzov Do you know when it's planned to make it possible to distinguish between those two?

**Comment by mortenfyhn** [comment]
Regarding "too close" vs. "out of range": The OS1 datasheet mentions

> 0 m - 0.3 m blockage detection flag to indicate object within 0.3 m (v2.0 beta feature)

Doesn't that mean that it should be able to detect "too close" as something different from "out of range"?

**Comment by versatran01** [comment]
Where is this flag?

**Comment by i-sheremet** [comment]
Does the new Firmware 2.1.1 solves this issue?

**Comment by dgarbuzov** [comment]
Sorry for the late response:

> Just to confirm, 0 means "out of range", anything >0 should be treated as a hit, is this correct?

@versatran01: 0 means there is no valid range reading (the way conversion from raw range readings to coordinates in the lidar frame is defined, this would actually be *inside* the sensor). That could either be out of range, within the minimum range, or just a missed detection.

@i-sheremet I can't comment on feature timelines, but I can confirm that the general laser link above isn't accurate, but for further questions about min/max range detection, please contact Ouster support.

**Comment by versatran01** [comment]
May I ask again where is the block detection flag?

**Comment by mortenfyhn** [comment]
It would be really nice to have this flag made available in the point clouds created by this ROS driver.

**Comment by peci1** [comment]
> Benjamin Freret commented:
> Hello Martin,
> Thanks for reaching us. This flag is not available, even though it is said in the documentation that it is.
> Apologies for this inconvenience,
> Benjamin, Customer Success Engineer

**Comment by shubham-shahh** [comment]
> > Benjamin Freret commented:
> > Hello Martin,
> > Thanks for reaching us. This flag is not available, even though it is said in the documentation that it is.
> > Apologies for this inconvenience,
> > Benjamin, Customer Success Engineer

is this flag available now?
