### ISSUE TITLE
Working with multicast configured units?

### ISSUE THREAD

**Issue by canvasus** [ouster-lidar/ouster_example#251]
Is there a way to connect to multicast-configured OSx units with the Python SDK?

**Comment by dgarbuzov** [comment]
Setting "udp_dest" to a multicast address with `client.set_config` and listening for packets seems to work for me. Are you running into any particular issues or looking for more documentation?

**Comment by canvasus** [comment]
Ok thanks. On our system I could not initialize the clients. I will try this again and come back with more details.

For clarity: did you test on Windows or Linux, and do you think there could be different behaviour?

**Comment by dgarbuzov** [comment]
I tested on linux. I'd be surprised if multicast UDP behaved differently on Windows, but I could be wrong.

Re failure to initialize: that happens when the client is unable to read metadata from the sensor over TCP, so it might be unrelated to the udp_dest setting.

**Comment by dgarbuzov** [comment]
I think I was confusing multicast with broadcast addresses. Feel free to reopen
