### ISSUE TITLE
Software timestamping for Ouster LiDAR

### ISSUE THREAD

**Issue by yulan0215** [ouster-lidar/ouster_example#252]
Hi!
I would like to ask a question that I would like to use "chrony+PTP 1588" to synchronize my Ouster LiDAR. 
The problem is that I have the Jetson Nano, which can only support software timestamping. In the Ouster LiDAR manual:  https://data.ouster.io/downloads/software-user-manual/software-user-manual-v2p0.pdf
The instruction only mentions the Hardware timestamping method.
I followed the instruction: set_config_param timestamp_mode TIME_FROM_PTP_1588  and then: reinitialize and: write_config_txt.
But when I finished the mode setup, I do not know how to setup the ptp4l and chrony for the ouster lidar.
Do you know any instruction about the software for the Ouster LiDAR?
I will appreciate if you can tell me !

**Comment by kairenw** [comment]
Apologies that we did not respond at the time.

Instructions for setting up PTP can be found in the sensor docs [here](https://static.ouster.dev/sensor-docs/image_route1/image_route3/appendix/ptp-quickstart.html)

Hope that helps
