### ISSUE TITLE
Difference in performance between batch_to_iter and batch_to_scan?

### ISSUE THREAD

**Issue by ntthuy11** [ouster-lidar/ouster_example#253]
I updated my Ouster 128 to firmware 2.0, but I had my `ouster_client` since the version 1.13 (which `batch_to_iter` was used). Now I am working on upgrading `batch_to_iter` to batch_to_scan (I am using non-ROS middleware so I have to rewrite a bit of codes). What are the main differences between `batch_to_iter` and `batch_to_scan` performance-wise? Any expected issues I need to consider when I keep using `batch_to_iter` but updating the rest (data structure, netcompat, etc)?
Thanks!

**Comment by dgarbuzov** [comment]
Performance should be comparable, though the API has changed quite a bit. The old `batch_to_iter` function should still work, if you need something more flexible.

**Comment by ntthuy11** [comment]
thank you! I tested. `batch_to_iter` still worked great for me after the update.
