### ISSUE TITLE
picking up specified frame from pcap file

### ISSUE THREAD

**Issue by kazu0622** [ouster-lidar/ouster_example#260]
I'm trying to design python app to retrieve frame data from pcap file.
The frames I got seem to be skipy despite I gave consecutive number for scans.

I made a copy  your sample code and modified like this:
metadata = client.SensorInfo(metadata_path)
source = pcap.Pcap(pcap_path, metadata)
scans = client.Scans(source)
# iterate `scans` and get the 84th LidarScan
for i in range(0,100)
    scan = nth(scans, i)
    ranges = scan.field(client.ChanField.RANGE)

I'd like to know where the problem is.

I'll attach 2 image files I got.
![img_21](https://user-images.githubusercontent.com/47018819/121514994-9eb30600-ca27-11eb-8e0a-862c8dc751b6.jpg)
![img_22](https://user-images.githubusercontent.com/47018819/121515038-ab375e80-ca27-11eb-8846-a897076971f1.jpg)

Thanks.

**Comment by kairenw** [comment]
Hi @kazu0622,

You're skipping the scans in between by using [`nth`](https://more-itertools.readthedocs.io/en/stable/api.html#more_itertools.nth). I would try replacing your loop with `for scan in scans` to iterate through your pcap.

**Comment by kazu0622** [comment]
Hi @kairenw,
Thank you for your quick response and I appreciate your tips.
I was able to solve this issue.

Thanks.
