### ISSUE TITLE
Range field of Point.h is always equal to the reflectivity value

### ISSUE THREAD

**Issue by Betschler** [ouster-lidar/ouster_example#264]
Hi,

The range and the reflectivity value are always the same. A fix would be lovely :)

> I am working with an Ouster OS1-32 Gen 2 as a perceptional Sensor for a positioning system. The firmware of the sensor is v2.0.0. 
> I downloaded the package, fired it up in my room, and watched it with rviz.
> Somehow the range value seems not to be right. The image shows my room and the stuff inside. The colormap is not inverted and displays the range value by intensity.
> 
> The very reflective jacket gets a way higher range value than everything around it. It seems to be a bug in the software package since it looks fine when watching the range value in OusterStudio.
>  
> Here again the image by rviz with the code of this website.
> ![image](https://user-images.githubusercontent.com/47030413/122610492-0ac4e800-d080-11eb-8442-67c8ebe7c668.png)
> Here in OusterStudio:
> ![image](https://user-images.githubusercontent.com/47030413/122610836-92125b80-d080-11eb-80e5-1f8a2658875b.png)
> 
> After a while of playing around with the point cloud showing this strange behaviour, I noticed that the range and the intensity value of the range and reflectivity are the same.

Thanks in advance.

**Comment by kairenw** [comment]
Hi @Betschler, 

That's correct: the sensor returns range measurements, which should return lower values for closer objects and higher values for farther-away ones. 

I'm having a little trouble interpreting what your screenshot indicates. Perhaps you could tell us what you're looking for and how you generated the cloud?

**Comment by versatran01** [comment]
You might want to check if the colormap is inverted in rviz

**Comment by Betschler** [comment]
> Hi @Betschler,
> 
> That's correct: the sensor returns range measurements, which should return lower values for closer objects and higher values for farther-away ones.
> 
> I'm having a little trouble interpreting what your screenshot indicates. Perhaps you could tell us what you're looking for and how you generated the cloud?

Hi, I just downloaded the package, fired it up in my room, and watched it with rviz. The firmware of the OS1-32-Beam Gen2 is v2.0.0. 
Somehow the range value seems not to be right. The image shows my room and the stuff inside. The colormap is not inverted and displays the range value by intensity.

The jacket which is very reflective gets a way higher range value than everything around it. It seems to be a bug in the software package since when watching the range value in OusterStudio it looks fine.
 
Here again the image by rviz with the code of this website both .
![image](https://user-images.githubusercontent.com/47030413/122610492-0ac4e800-d080-11eb-8442-67c8ebe7c668.png)
Here in OusterStudio:
![image](https://user-images.githubusercontent.com/47030413/122610836-92125b80-d080-11eb-80e5-1f8a2658875b.png)

Best regards,
Daniel

**Comment by kairenw** [comment]
@Betschler -- Oh I see! Thank you for the clarifications.

I believe we fixed this bug in PR #239. Are you on the latest version?
