### ISSUE TITLE
Different PTP Delays on Different Ouster LiDARs

### ISSUE THREAD

**Issue by yucedagonurcan** [ouster-lidar/ouster_example#272]
Hello All,

I have three questions actually, but before that I will explain my system:

- **Ethernet Card:** Intel I210 with 10000Mb/s
- **LinuxPTP Version**: 1.8
- Test Conducted with 6 different Ouster LiDARS all with v2.1.1 as firmware.
- LiDARs in test:
   1. OS-1-16-A2:  1024x10 -> _default-relaxed_
   2. OS-0-32-U0:  1024x10 -> _default-relaxed_
   3. OS-1-32-U1:  1024x10 -> _default-relaxed_
   4. OS-0-32-U1:  1024x10 -> _default-relaxed_
   5. OS-2-128:  1024x10 -> _default-relaxed_
   6. OS-1-128:  1024x10 -> _default-relaxed_
- PTP4L Configuration:
`[Service]
ExecStart=
ExecStart=/usr/sbin/ptp4l -f /etc/linuxptp/ptp4l.conf -p /dev/ptp0`
- PHC2SYS Configuration:
`[Service]
ExecStart=
ExecStart=/usr/sbin/phc2sys -a -r`
- ROSTopic Delay results:
   1. OS-1-16-A2: 0.110  
   2. OS-0-32-U0: 0.120
   3. OS-1-32-U1: 0.110 
   4. OS-0-32-U1: 0.147 
   5. OS-2-128:   0.128
   6. OS-1-128:   0.120

**Questions:** 
1. Does this numbers of divergence is normal and inside the limits of general LiDAR intra-machine synchronization with PTP?
2. Why variance in such a drastic way is happening between LiDARs? First 128-channelled LiDARs were worse than the others but gradually they become a normal if we look at the other LiDARs.
3. Does `rostopic delay` is the go to way to find out these time differences?

**Comment by Jaetriel** [comment]
@yucedagonurcan I am reviving this to ask if you had any luck finding an answer to why these differences between the LiDARs are happening and if they are normal? I am also curious to find out
