### ISSUE TITLE
running ouster_client_example 

### ISSUE THREAD

**Issue by KatuunuXVI** [ouster-lidar/ouster_example#273]
I'm currently working with a NVIDIA Jetson and I have it connected to a lidar sensor via ethernet cord (through a upoe switch) when I run ipconfig, the given ip address from eth0 is the following,

```
eth0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 169.254.1.250  netmask 255.255.0.0  broadcast 169.254.255.255
        ether 48:b0:2d:15:da:cb  txqueuelen 1000  (Ethernet)
        RX packets 6130323  bytes 7015456418 (7.0 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1227997  bytes 67763352 (67.7 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 37
```

However when running the example code, as follows (169.168.0.208 is the ip address of the Jetson),
`./ouster_client_example 169.254.1.250 169.168.0.208`
I get a connection failure. Is there a method to verify that a connection to the lidar sensor from a linux environment is possible, or a method to verify the IP address of the sensor?

**Comment by pulver22** [comment]
I actually have the same error while connecting the LIDAR to a ZOTAC.

**Comment by arunumd** [comment]
You can try `./client_example 169.254.1.250 ""`
