### ISSUE TITLE
Convert recorded rosbag file to numpy array

### ISSUE THREAD

**Issue by baheytharwat** [ouster-lidar/ouster_example#276]
I have a recorded rosbag file for OS1-64 lidar and tried to read the point cloud of each message through the topic `/os1_cloud_node/points` and convert it into a numpy array using different libraries such as pcl and pypcd but I got a corrupted point cloud. Although I visualized the rosbag file using RVIZ and it seems OK. 
Do you provide any tutorials or scripts that can help me converting a message (PointCloud2) from `/os1_cloud_node/points` topic to a numpy array that contains x,y,z and intensity?

**Comment by hujunhan** [comment]
I have a similar problem, did you solve it?

**Comment by kairenw** [comment]
Hi @hujunhan can you start a new issue for this, thanks!
