### ISSUE TITLE
data stops after certain time - cfg set_rcvtimeout(): Bad file descriptor

### ISSUE THREAD

**Issue by TheRealKaufmann** [ouster-lidar/ouster_example#281]
Hi there,

I am using the Ouster OS-1 32 Gen.2 with the ouster_ros driver. 
It is running fine, but after 4 minutes or so, the datastream on the ros topics suddenly stops. I have tried over 21 times in different conditions to exclude things like overheating issues.
Whenever the datastream stopped, no errors or warnings occured. But when trying to launch the node again, it always reports an error `[ERROR] [1628167764.565069272]: Failed to initialize sensor at: os-122123000698.local
[ERROR] [1628167764.577518424]: Calling config service failed
`
To this point I was using the ouster_ros driver at commit [b8b23c35d7b719d69341a438d386a801688aa6a4](https://github.com/ouster-lidar/ouster_example/commit/b8b23c35d7b719d69341a438d386a801688aa6a4)

Now I have upgraded to master. 
The same thing happens, but when trying to start the node again one additional message occurs.
`cfg set_rcvtimeout(): Bad file descriptor`

Can you please point me in a direction here? What does that mean?

Thanks,
Tom

**Comment by kairenw** [comment]
Hi @TheRealKaufmann,

Sorry for the delay in reply. I think this is unlikely to be an issue with the ouster_ros driver, so I'm going to ask you to send a ticket to [Ouster support](https://ouster.atlassian.net/servicedesk/customer/portal/8/group/22/create/86). You may want to take a look at the diagnostic tab on your sensor homepage (for your sensor, this would be at http://os-122123000698.local).

Closing this ticket, but feel free to re-open it if it seems I didn't understand something.

Thanks!
