### ISSUE TITLE
.pcap reader in matlab

### ISSUE THREAD

**Issue by pavankumarbn** [ouster-lidar/ouster_example#283]
Hello All,

I have ouster recorded .pcap data. How can I read this data using matlab? Please help me out. 

Thanks,
Pavan

**Comment by kairenw** [comment]
Hi @pavankumarbn,

Could you let us know a little bit of your use case? You may find it easiest to read your recorded .pcap using the [Ouster Python SDK](https://static.ouster.dev/sdk-docs/quickstart.html), and save the loaded data from numpy into `.mat` or .csv to port into matlab.

**Comment by pavankumarbn** [comment]
Hi @kairenw, Many thanks for your response. Sure I will try it out as you suggested. We are working on object detection and tracking using ouster data on matlab platform. Regarding conversion, please let me know if there is any demo example on this ?

**Comment by kairenw** [comment]
Hey @pavankumarbn,

We don't have a demo example, but it should be fairly straightforward using something like scipy's [savemat](https://docs.scipy.org/doc/scipy/reference/generated/scipy.io.savemat.html). You can try working off our save to csv [example](https://static.ouster.dev/sdk-docs/examples.html#converting-pcaps-to-csv). Let us know how it goes!

**Comment by pavankumarbn** [comment]
Hi @kairenw, Thank you for your response. It is much appreciated. I followed as you suggested and worked on the CSV example. When I run `python3 -m ouster.sdk.examples.pcap OS1_128.pcap OS1_2048x10_128.json pcap-to-csv --scan-num 5` ; it is working fine. However, when I try to run the complete source code as given it is throwing some errors. I will post the complete code in another open issue. Please help me with that.

**Comment by kairenw** [comment]
Great! I'm going to close this out and keep working with you on the other ticket. Thanks!
