### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by ShahJinali** [ouster-lidar/ouster_example#297]
Hello all,

I got an ouster lidar OS2-128. Lidar is directly connected to host system[windows] via usb ethernet network cable. I tried to run an ouster example on windows and it works perfectly fine. I also had virtual machine on windows and it had ubuntu 20.04 running on it. When I tried to run the ouster example on virtual machine it gives the "Failed to connect " error. Though, I was able to ping the lidar on ubuntu using "ping -4 -c3 < sensor-hostname >.local".

What is the possible solution for this?

Thank you,
Jinali Shah.

**Comment by kairenw** [comment]
Hi @ShahJinali,

I think this might be a question for our support team. You can contact Ouster support [here](https://ouster.atlassian.net/servicedesk/customer/portal/8/group/22/create/86).

Closing this ticket now. Feel free to repoen if you're not getting a response there.
