### ISSUE TITLE
Have to relaunch node to replay a second bag

### ISSUE THREAD

**Issue by mortenfyhn** [ouster-lidar/ouster_example#3]
I'm able to replay logs and visualize with rviz by following your instructions (roslaunch node with replay=true, then run rosbag play, then run rviz). If I want to replay another log afterwards, however, I have to restart both rviz and the ros node to make it work, otherwise rviz just displays nothing.

**Comment by dgarbuzov** [comment]
Good idea! b72a87480e51cc7d3fefd1db05e52ba6f488d5b6 should fix that.

**Comment by mortenfyhn** [comment]
That seems to work! Thank you.
