### ISSUE TITLE
Running ouster lidar with i7 gen 11

### ISSUE THREAD

**Issue by snakehaihai** [ouster-lidar/ouster_example#309]
Hi 
I`m not newbee so lets just cut to point.

I`m able to run the LIDAR with gen 10 i7 NUC , dji manifold2C and gen 8 i7 notebook. 

In recent NUC 11. I have a problem in opening the web config  @ http://os-XXXXXXX.local for the newer NUC. 

When running driver, i got the error of

getaddrinfo: name or service not known.

So I guess its the newer kernel that could not resolve the address?

I tried getaddrinfo of localhost, it returns me of correct one. So have you guys tested it on NUC 11 already?

**Comment by kairenw** [comment]
Apologies. Closing as this is an old issue. If you are still having issues, please feel free to re-open
