### ISSUE TITLE
Failed to initialize client

### ISSUE THREAD

**Issue by kalai86** [ouster-lidar/ouster_example#310]
Hi,

I have build thesource code and connect lidar and tried with below commands 
I am trying this with linux board.

./simple_viz os1-122xxxxxxxxx
./simple_viz os-122xxxxxxxxxx

which ends with the below mentioned error

Using automatic UDP destination
Waiting for sensor os1-122xxxxxxxx to initialize ...
cfg getaddrinfo(): Name or service not known
Failed to initialize client

Please help to solve the problem.

Thanks and regards,
Kalai

**Comment by kairenw** [comment]
Hi @kalai86,

Sorry for the long wait. Do you mind submitting your issue through the [Ouster customer support portal](https://ouster.atlassian.net/servicedesk/customer/portal/8)? Think they'll be able to be more hands on. 

Closing for now.
