### ISSUE TITLE
PCL dependency on Ubuntu 20.04: PCL can not be found on this machine

### ISSUE THREAD

**Issue by F1iX** [ouster-lidar/ouster_example#314]
When compiling the ouster_ros package on a clean Ubuntu 20.04, I get the error
```
-- ==> add_subdirectory(ouster_lidar/ouster_ros)
CMake Error at /lib/x86_64-linux-gnu/cmake/pcl/PCLConfig.cmake:62 (message):
  PCL can not be found on this machine
```

Looks like this is an issue with PCL itself which can be fixed with
```
sudo mkdir /lib/x86_64-linux-gnu/cmake/pcl/include
sudo ln -s /usr/include/pcl-1.10/pcl /lib/x86_64-linux-gnu/cmake/pcl/include/pcl
```

Perhaps you can fix it upstream or include the workaround in your README. Thanks!

**Comment by dgarbuzov** [comment]
That's odd, I don't have this issue in a fresh container (ros:noetic-ros-core) running through the build instructions from the readme. The Dockerfile has been passing CI, as well. It's also a bit surprising that linking the headers under the cmake directory would do anything useful.

Is it possible something overwrote your pcl package files? What's the output of `dpkg -l '*pcl*'` on your system? Might be worth updating and reinstalling `ros-noetic-pcl-ros` to see if that fixes it.

**Comment by kairenw** [comment]
I also did not have success replicating this error. 
Going to close this ticket now.

**Comment by millerluki** [comment]
Got the same error after upgrading all packages with `sudo apt update && sudo apt upgrade`
The fix mentioned from @F1iX doesn't work for me
`sudo mkdir /lib/x86_64-linux-gnu/cmake/pcl/include
sudo ln -s /usr/include/pcl-1.10/pcl /lib/x86_64-linux-gnu/cmake/pcl/include/pcl` 

After reinstalling ROS 2 all works as expected
