### ISSUE TITLE
Unexpected UDP data packet length = 3392 with OS-16A

### ISSUE THREAD

**Issue by aditya-c2512** [ouster-lidar/ouster_example#315]
I'm using the Steve Macenski fork of the ros package. I followed it step by step but when I entered the roslaunch command, I keep getting a 
```
unexpected UDP data packet length = 3392
```

What seems to be the problem here? Because I don't see anything being published as well.

**Comment by kairenw** [comment]
Hi @aditya-c2512,

My guess is that your ports are misconfigured/something else is using them, but it's hard to know without more information.

**Comment by pradumn203** [comment]
I used the same package (Steve Macenski) and getting same error. Anyone knows a fix?
I am subscribing to Pointcloud2 topic but not getting the Pointcloud data
Only IMU data is coming on rviz alonwith the following error in the terminal:

unexpected UDP data packet length = 3392
