### ISSUE TITLE
RLException: [ouster.launch] is neither a launch file in package [ouster_ros] nor is [ouster_ros] a launch file name

### ISSUE THREAD

**Issue by schleptech** [ouster-lidar/ouster_example#317]
Followed instructions in setting up ros sample code:

https://github.com/ouster-lidar/ouster_example#example-ros-code

Keeping getting this error after running:

roslaunch ouster_ros ouster.launch sensor_hostname:=OS-992105000463
RLException: [ouster.launch] is neither a launch file in package [ouster_ros] nor is [ouster_ros] a launch file name
The traceback for the exception was written to the log file

Yes, I have sourced the setup.bash at /myworkspace/devel/setup.bash after building

**Comment by kairenw** [comment]
Hi @schleptech,

Sorry to hear that. Would you mind pasting in the logs specifically from when you source, build, and try to launch? That might help us narrow down what's happening.
