### ISSUE TITLE
Failed to run on Windows

### ISSUE THREAD

**Issue by Deave-tech** [ouster-lidar/ouster_example#318]
I followed the instructions step by step, but it still didn't work.
I need help,Thanks!

![微信截图_20211117143607](https://user-images.githubusercontent.com/60037974/142147354-46b8c8d1-b565-46af-acbd-56f1fc5e7ee4.png)

**Comment by kairenw** [comment]
Hi @Deave-tech,

It's likely that the second argument, the data destination IP, is not correct. Try setting it automatically by leaving the argument blank or configuring it through the sensor homepage in your browser.

**Comment by Deave-tech** [comment]
firewall not closed，thanks
