### ISSUE TITLE
jetson xavier nx + OS0 lidar

### ISSUE THREAD

**Issue by junjie-Hub** [ouster-lidar/ouster_example#324]
Hi! I want to configure ouster os0 on jetson xavier nx, is there any solution?

**Comment by junjie-Hub** [comment]
when I used commend:nmcli con modify eth1 ipv4.method link-local ipv4.addresses "
![Screenshot from 2021-12-02 16-32-14](https://user-images.githubusercontent.com/84827187/144377787-642fc532-b9ed-43c8-885b-e8e6762cc61e.png)
But if it is correct, the following result should appear.
![3](https://user-images.githubusercontent.com/84827187/144379431-ec03abaf-d473-462d-9084-cb66c3e95731.png)

 So i need your help.......

**Comment by kairenw** [comment]
Hi @junjie-Hub, Think it's likely you don't have the interface `eth1`. You can identify the interface by using `ifconfig`. Try following the directions under 17.3.4 "Determining the IPv4 Address of the Interface" in our [user manual](https://data.ouster.io/downloads/software-user-manual/software-user-manual-v2.1.x.pdf)

**Comment by junjie-Hub** [comment]
> 

OK. Thank you for your response. I will try as you said.

**Comment by kairenw** [comment]
Let us know if you have other issues. Closing ticket now.
