### ISSUE TITLE
Python example code does not work

### ISSUE THREAD

**Issue by themightyoarfish** [ouster-lidar/ouster_example#326]
I have an OS1 sensor, and `pip install`ed the ouster sdk. Some examples work:

```
> python -m ouster.sdk.examples.client  os-122142000686.local fetch-metadata
example: fetch-metadata
Retrieved metadata:
  serial no:        122142000686
  firmware version: v2.1.3
  product line:     OS-1-128
  lidar mode:       2048x10
Writing to: os-122142000686.local.json
```

But actually retrieving data does not. I can successfully use the cpp client on the same computer (macos 10.15.7).

```
> python -m ouster.sdk.examples.client  os-122142000686.local plot-xyz-points
example: plot-xyz-points
[…] 
venv/lib/python3.8/site-packages/ouster/client/core.py", line 254, in flush
    raise ClientTimeout(
ouster.client.core.ClientTimeout: No packets received within 1.0s
```

**Comment by themightyoarfish** [comment]
Changing the timeout does not help, I can tell the scanner is not starting as it does with the C++ code.

**Comment by themightyoarfish** [comment]
The scanner is connected via Link Local address, and should use the default ports.

**Comment by kairenw** [comment]
Hi @themightyoarfish, 

Any chance you haven't set the udp_dest? Try going to the sensor homepage: http:<sensor-hostname.local>/config and using "set local" (remember to "Apply Config" after that).

**Comment by themightyoarfish** [comment]
The C++ code deals without, I had assumed the Python code to behave the same and the sensor to send to whatever origin address it received commands from.

**Comment by kairenw** [comment]
Yes, taht's correct. The Python `plot-xyz-points` example does not auto-configure udp_dest, but the cpp example `ouster_client_example` does. Let me know if that solves your issue or if it remains.

**Comment by dgarbuzov** [comment]
Think the only reason the examples (other than `configure-sensor`) don't change the configuration is that it's annoying to wait for the sensor to reinitialize on every run. The intention was that people would go through the examples section of the docs top-to-bottom, but we should at least make that more clear.

**Comment by themightyoarfish** [comment]
Wait, so the long startup time is because of this? That has been an annoyance with my c++ client code also.

**Comment by dgarbuzov** [comment]
Yep. There's two overloads of `init_client()` -- one updates a few config parameters and reinitializes the sensor, the other skips that step and immediately fetches metadata and begins listening for UDP packets.  The example code uses the former.

**Comment by sradmard** [comment]
I was running into the same issue, and setting `udp_dest` resolved the issue for me as recommended.

**Comment by kairenw** [comment]
Think this is probably resolved. Closing now.

**Comment by kairenw** [comment]
Reopning to note that the requested enhancement is: rework examples section of docs so that it's clear you need to configure the sensors first before running some of the examples.

**Comment by kairenw** [comment]
Issue should be addressed. Thank you!

**Comment by MarcoCia** [comment]
> Stavo riscontrando lo stesso problema e l'impostazione `udp_dest`mi ha risolto il problema come consigliato.

Hi, Can you help me to solve the problem? 
I receive the error "ouster.client.core.ClientTimeout: No packets received within 1.0s"

**Comment by kairenw** [comment]
Sure, could you go to your sensor homepage (http://[SENSOR_HOSTNAME].local) and then hit the "Configuration tab" and upload a screenshot?

**Comment by will22thomas** [comment]
I'm having a similar problem: every now and then it really acts up and I have to unplug the lidar from the wall, or the computer, and re-configure it, and reset the UDP destination address (or any combination of these solutions). Sometimes it eventually works, sometimes it doesn't. I get this error: ouster.client.core.ClientTimeout: No packets received within 2.0s
Any ideas?

**Comment by kairenw** [comment]
hi @MarcoCia and @will22thomas in general it's a bit easier for us if you start a new issue. Just tag me on the new one and we can talk there (:

**Comment by sriram2989** [comment]
same issue with by any chance can i have a solution
