### ISSUE TITLE
No lidar profile found

### ISSUE THREAD

**Issue by liubonan123** [ouster-lidar/ouster_example#329]
[ INFO] [1639486430.480654550]: rviz version 1.13.18
[ INFO] [1639486430.480688354]: compiled against Qt version 5.9.5
[ INFO] [1639486430.480694989]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1639486430.493057358]: Forcing OpenGl version 0.
[ INFO] [1639486430.630479935]: Stereo is NOT SUPPORTED
[ INFO] [1639486430.630543841]: OpenGL device: llvmpipe (LLVM 10.0.0, 128 bits)
[ INFO] [1639486430.630580020]: OpenGl version: 3.1 (GLSL 1.4).
[ INFO] [1639486448.436296124]: Sensor initialized successfully
[ INFO] [1639486448.439777644]: Wrote metadata to /home/bonliu/bag/meta.json
WARNING: No lidar profile found.
[ INFO] [1639486448.442017989]: Using lidar_mode: 2048x10
[ INFO] [1639486448.442075051]: OS-1-128 sn: 122146000203 firmware rev: v2.1.3

**Comment by kairenw** [comment]
Hi @liubonan123,

Assuming your sensor is Rev5 or below (which you can check using the part number available on the sensor homepage), and you recorded this data before our latest software updates to master, this warning is fine. The client will default in the case that there is no lidar profile in the meatdata to using the `LEGACY` lidar profile, which should match what your sensor is using.

Closing this ticket now.
