### ISSUE TITLE
Function prints to cout

### ISSUE THREAD

**Issue by themightyoarfish** [ouster-lidar/ouster_example#337]
https://github.com/ouster-lidar/ouster_example/blob/ad837d005e607e0ec1a16e967705cce15b0fb851/ouster_client/src/types.cpp#L608

It would be better to throw an exception or something, instead of polluting client code's standard output.

**Comment by Samahu** [comment]
PR https://github.com/ouster-lidar/ouster_example/pull/456 introduced `init_logger` method which enables the user to direct warning and error messages to a file rather than to the console.
