### ISSUE TITLE
the noise of inner IMU

### ISSUE THREAD

**Issue by txyxy** [ouster-lidar/ouster_example#346]
Hi,
   
I'm now using a os0-64 lidar to test a slam algorithm which needs to know the noise of inner IMU.  Is there any suggestions to calibrate the noise?  I need to collect data of static IMU while the lidar shakes after it's opened. The tool I use to calibrate noise is [https://github.com/gaowenliang/imu_utils](url) .

Thanks.

**Comment by kairenw** [comment]
I think you can just use `ouster_ros` to record two hours of stationary lidar data, in accordance to the instructions on https://github.com/gaowenliang/imu_utils
