### ISSUE TITLE
2D Floor plan from a 3D point cloud

### ISSUE THREAD

**Issue by anilsrik** [ouster-lidar/ouster_example#347]
**This is not an issue but more sort a help doc request** 

We are doing a mapping system for buildings. To do this we need to generate a 2D floor plan of a floor scan  (essentially a pointcloud) 

I'm trying figure this and any help here is greatly appreciated.

**Comment by kairenw** [comment]
Hi @anilsrik,

You're probably interested in various SLAM algorithms. People often use [LeGO-LOAM](https://github.com/RobustFieldAutonomyLab/LeGO-LOAM) and/or [A-LOAM](https://github.com/HKUST-Aerial-Robotics/A-LOAM) as a starting point. Once you get a 3D Map output, you can always just project that into 2D for a 2D floor plan.

If you wanna see what 3D Mapping output might look like, you can try uploading a bag recording of you walking through a building to [Ouster's Web SLAM](https://webslam.ouster.dev/). Although SLAM is something it'd be lovely to support, at this point it would be quite far in the future (a year or more out at least) before we could support it an open-source way.

Hope that helps! Gonna close this out, but feel free to re-open with more questions.
