### ISSUE TITLE
LICENSE installs without namespace

### ISSUE THREAD

**Issue by themightyoarfish** [ouster-lidar/ouster_example#349]
https://github.com/ouster-lidar/ouster_example/blob/13ea8e8b8a4951fb630dbc9108666995c8443bf6/CMakeLists.txt#L68

Is it intended to install to `prefix/share/` directly? Other libraries install to `prefix/share/licenses/<libname>/`

**Comment by kairenw** [comment]
Should be addressed by https://github.com/ouster-lidar/ouster_example/pull/420. Closing this out now.
