### ISSUE TITLE
Under what licence sample data is distributed?

### ISSUE THREAD

**Issue by r7vme** [ouster-lidar/ouster_example#379]
Hello, under what licence [sample data](https://static.ouster.dev/sdk-docs/sample-data.html#download-data) is distributed? For example, [OS0 128 Rev 06 Urban Drive (Dual Returns)](https://data.ouster.io/sdk-samples/Rev-06-fw23/OS0-128_Rev-06_fw23_Urban-Drive_Dual-Returns.zip) .

**Comment by r7vme** [comment]
@kairenw thanks for clarification!

**Comment by kairenw** [comment]
We've updated our docs here: https://static.ouster.dev/sdk-docs/sample-data.html#download-data to make note of the License! Thanks again for asking about this! Closing this issue out now.
