### ISSUE TITLE
How to configure dead/blind zone for ouster lidar

### ISSUE THREAD

**Issue by shubham-shahh** [ouster-lidar/ouster_example#380]
Hi @kairenw ,
I want to configure the blind zone of my sensor, I want to ignore certain things in the periphery, which are close to the sensor, hence I would like to configure a blind zone around the sensor

Thanks

**Comment by kairenw** [comment]
Hi @shubham-shahh,

There currently is no way to do set a blind/dead zone around the sensor based on range. If you have some things that are in a set position in relation to the sensor, say the sensor mount which is visible always between some azimuth degrees from the sensor, you might be interested in the azimuth window configuration parameter. Please refer to the sensor documentation available at the Ouster Downloads page: https://ouster.com/downloads/ for more details on the azimuth window.

For further issues of this type, I suggest contacting [Ouster support](https://ouster.atlassian.net/servicedesk/customer/portal/8)! While we're happy to answer these questions on the sensor as they arise on Github, this github is for the Ouster SDK and focuses on that.

Closing, but feel free to reopen.
