### ISSUE TITLE
No images when replaying bag files

### ISSUE THREAD

**Issue by pauldeee** [ouster-lidar/ouster_example#384]
Hi,

Is it possibleto get image topics when replaying a bag? It seems they are published by default when running the node live, but when I launch in replay mode there are no images.

ROS Noetic, Ubuntu 20.04 LTS
os1-64 firmware 2.3.0
Client version: 0.4.0+43107a1-release

**Comment by Samahu** [comment]
Hi @pauldeee, if you specify `viz:=true` in the launch command then you should be able to see the images published. This shouldn't be the case and will try to address it ASAP. Can you please verify that you are able to stream the images in replay mode by set the **viz** argument to **true**?

**Comment by pauldeee** [comment]
Hello @Samahu,

Okay, seems some args have changed from past versions. That seems to do it. Thanks.
