### ISSUE TITLE
Missing part of lidar points

### ISSUE THREAD

**Issue by Tinyyyy** [ouster-lidar/ouster_example#387]
Hi, 
I have some problems with OS1 64/32. As shown in the video, some reflective stripes are stuck on the wall which produce points cloud with high reflectivity. The surrounding points are abnormally missing. But when the reflective stripes are covered with some materials, all of these points appear. I am confused about this phenomenon and I want to know how to fix it. The missing points are important to me. Thanks!

https://user-images.githubusercontent.com/29725150/170519864-0ca021d5-1ac1-43c1-b52e-a75048cb99be.mp4

**Comment by kairenw** [comment]
HI @Tinyyyy,

If you don't mind, I'm going to point you to our [sensor support team](https://ouster.atlassian.net/servicedesk/customer/portal/8/group/22/create/86). This github answers questions on the C++/Python SDK, so we're not the best people. 

Just send in the screenshot, and this same write-up. They may be able to talk to you about why and how.

Closing this out, but feel free to reopen with more comments.
