### ISSUE TITLE
Enable sdk in WPF

### ISSUE THREAD

**Issue by omy5123** [ouster-lidar/ouster_example#388]
Hi, I want to collect data in C# wpf environment with Osteros2 lidar sensor and visualize PointCloud data.

The software design we are thinking of is as follows.
1. Build c++ Example File → .Lib file
2. Create c++/cli Class Library Project
3. Library file link
4. Create Wrapping code to output dll file
5. Reference dll in C#

Do you think examples using C# or above are possible? I'd appreciate it if you could answer!

The function I'm thinking about is
1. Sensor connection
2. Data collection (.pcap)
3. Real-time visualization by collecting 360 degree frame data by receiving udp data.

Thank you!!

**Comment by twslankard** [comment]
Thanks for your question, and apologies for the very late reply. We don't have plans to add C# support directly to ouster-sdk. However, it's likely you can do this on your own using tools such as https://github.com/mono/CppSharp.

Best Regards,

Tom
Staff Software Engineer
Ouster, Inc.
