### ISSUE TITLE
Is it possible to get 2D lidar image as they look in ouster studio?

### ISSUE THREAD

**Issue by wesKoi** [ouster-lidar/ouster_example#392]
So in ouster studio where I took some 2D images with OS1-32 I see my self in the images quite clearly in the 2D view of ouster studio the problem is that I can't really see my self in the black and white png images that I save from ouster studio.
Is there some kind of settings to save the 2D image to look the same as in ouster studio? 

Or some setting to make it easier annotating the images

**Comment by kairenw** [comment]
Hi @wesKoi, unfortunately the maintainers of this repo do not own Ouster Studio. 

I'm not sure how you intend to annotate the images, but it may be easier to work with the 2D images from our sensor using the [Ouster Python SDK](https://static.ouster.dev/sdk-docs/installation.html). The `field` function will give you a numpy 2D array of the desired field (range, signal, reflectivity, or near_ir), and from there you can use anything like matplotlib or opencv to visualize/save the 2D images.

Going to close this now, but feel free to re-open with more questions.
