### ISSUE TITLE
Allow inverting the simple-viz view for sensors mounted upside down.

### ISSUE THREAD

**Issue by sa-webb** [ouster-lidar/ouster_example#397]
Hi,

Many Road-side mounted LiDAR units are installed upside down due to camera mounting hardware. It would be nice to be able to invert the `simple-viz` visualization.

**Comment by kairenw** [comment]
Hi! This should be address by the latest `simple-viz` in 0.7.1 using the `--extrinsics` option! Thank you for your patience.
