### ISSUE TITLE
Using conan recipe on windows fails due to fpic

### ISSUE THREAD

**Issue by AustinMooreResonantSciences** [ouster-lidar/ouster_example#402]
This line fails because fpic was deleted from options since my platform is windows.
https://github.com/ouster-lidar/ouster_example/blob/64a6cbe6dff1eea0cb5a79d63b79acf11b68b16d/conanfile.py#L77
The following is a fix, but I'm a bit unsure about how I should go about fixing this? Fork, then add the commit and merge request?
```python
True if (not self.settings.os == "Windows" and self.options.fPIC) else False

**Comment by bexcite** [comment]
Fixed in https://github.com/ouster-lidar/ouster_example/pull/432
