### ISSUE TITLE
No packets received within 1.0s

### ISSUE THREAD

**Issue by Sergei1993SS** [ouster-lidar/ouster_example#407]
Good afternoon

I have two sensors OS-0-64-U02.
Both have configured UDP Port Lidar and UDP Port IMU (different on each lidar), they are connected via a gigabit switch. I set up a static IP for the lidars so that they are on the same subnet with the computer (Ubuntu 18.04). I started the stream in different streams (Python SDK) and for some time they worked, but one day one lidar stopped working, and the second one works. giving the error "No packets received within 1.0s". At the same time, simple-viz for a non-working lidar works fine.

At the same time, there were other incomprehensible things with the receipt of packets from the lidar, which either appeared or disappeared.
Tell me, what could be the matter?
Thank you!

**Comment by kairenw** [comment]
Hi @Sergei1993SS,

This sounds like a sensor support issue. Go ahead and report your issues [here ](https://ouster.atlassian.net/servicedesk/customer/portal/8)-- and they'll probably want a diagnostic bin, available through your sensor homepage.

I'll close this now, but feel free to re-open if this isn't resolved in the future.

**Comment by bdytx5** [comment]
seems like having ouster studio open and conncected to the sensor while running python commands can cause this

**Comment by kairenw** [comment]
Yes, unless you multicast, only one application will consume
