### ISSUE TITLE
Library should not print to cout

### ISSUE THREAD

**Issue by themightyoarfish** [ouster-lidar/ouster_example#408]
https://github.com/ouster-lidar/ouster_example/blob/b9bc5c3bd459fa1f04098021c764ecafb35e1408/ouster_client/src/client.cpp#L583

As this is library code, this should not spam cout.

**Comment by Samahu** [comment]
Resolved by https://github.com/ouster-lidar/ouster_example/pull/456, use `init_logger` method before connecting to the sensor.
