### ISSUE TITLE
Using IMU packets to correct scanner orientation?

### ISSUE THREAD

**Issue by DevinBayly** [ouster-lidar/ouster_example#411]
Hi there,

I'm working with a faculty member of my university to create visualizations of her ouster scans and presently we are struggling because the scanner was translated/rotated by an assistant during the course of many of her scans. To see the issue I'm talking about I'll include a partial screen recording made with `simple-viz` :

https://user-images.githubusercontent.com/11687631/182921574-465b05d1-bfea-4d7e-9ecc-5c6a7de31b5a.mp4

I'm less experienced with things like SLAM, so I was wondering if there's a way to use the IMU packets to offset the scanner's translation and rotation during these moments and get a more stable representation of the environment as a point cloud. If this is not the right approach should I be looking into some workflow that involves ROS to help perform a SLAM? Thanks for working hard to provide an SDK for us to use, and for any information that might help here.

**Comment by kairenw** [comment]
The sensor's IMU is not great, but it can be used for odometry if you really want. 
Was the sensor supposed to be stationary, or do you actually want to move it while taking the scans to create a map of the environment?
You don't necessarily need ROS to do SLAM or odometry, but many of the easily available libraries are ROS-based. It really depends what you're comfortable working with.

**Comment by DevinBayly** [comment]
Thanks for writing back!

> Was the sensor supposed to be stationary, or do you actually want to move it while taking the scans to create a map of the environment?

I think the intention of the faculty member and assistant was that moving the scanner would help create a map of the environment. That said there are long portions of time in which the scanner is stationary and the goal is to capture behavior of people moving about in the recorded space. 

>  You don't necessarily need ROS to do SLAM or odometry, but many of the easily available libraries are ROS-based. It really depends what you're comfortable working with.

I'd love to take the easiest path, and I've already messed a bit with ROS so that seems like a good route. Looking in the other issues I see a similar question #129 , is the ROS cartographer a system I could use for this? Or do you have other ones in mind when you mention the easily available libraries?
https://google-cartographer-ros.readthedocs.io/en/latest/index.html

**Comment by kairenw** [comment]
Mind contacting us through [customer support](https://ouster.atlassian.net/servicedesk/customer/portal/8)? This is getting a bit far afield from what this Github is for (support for our sensor SDK)! We sometimes help customers get started with SLAM using open-source code through our customer support. You can write in the support ticket that I (Kai Wong) asked for your request to be put through to me, and I'll follow up with support to let them know.

For any non future readers on this thread, I'll just say that we welcome these types of asks through our customer support generally. I'll also say that in addition to Ouster sensors workign with Cartographer, we've verified that our sensor works with [Lego LOAM](https://github.com/RobustFieldAutonomyLab/LeGO-LOAM) and [A-LOAM](https://github.com/HKUST-Aerial-Robotics/A-LOAM), these being pretty popular libraries as well.

Thanks, closing this ticket now. If you don't manage to reach me on the other side, please reopen.

**Comment by DevinBayly** [comment]
Sounds good, thanks so much for the redirect!
