### ISSUE TITLE
How to get live data stream by using CPP sdk? 

### ISSUE THREAD

**Issue by E-Dreamer-LQ** [ouster-lidar/ouster_example#413]
I found that use example.cpp can get  n scans's info, but I want to get runtime stream data by using cpp sdk. Looking forward to a quick reply.

**Comment by Samahu** [comment]
We don’t have a standalone example that shows how to stream live data at
the moment but if you are a bit familiar with ROS you can refer to the
‘os_node.cpp’ which does show how to connect to a sensor and stream imu and
LiDAR data from it, the ‘os_cloud.cpp’ code file shows how to convert the
the LiDAR packets to point cloud.

Hope this helps
-- 
*Ussama Naal*
San Francisco, CA
<http://ouster.com/>

**Comment by Samahu** [comment]
@E-Dreamer-LQ I haven't heard back from you so I don't know if my response was sufficient. So I will close this issue for now, you may re-open the issue again if you still need help with it.
