### ISSUE TITLE
pointcloud maximum intensity fluctuating in rviz when launching multiple LIDARs simultaneously.

### ISSUE THREAD

**Issue by sskulka** [ouster-lidar/ouster_example#414]
Hello,
I am running 4 ouster OS0 and 1 OS2 on my internship project vehicle. Each of the lidars has a static ip address and they connect to a network switch which in turn connects to the computer. I'm trying to record a rosbag with all of the lidars triggered for which I've defined a static_transform_publisher tf tree and then I'm launching the ouster_ros ouster.launch.
To avoid any throughput issues, I have the OS2 and ptp info (ptp is received from TM2000B connected to the switch) coming to the computer on the ethernet port on a particular subnet. The rest of the OS0 lidars are sending the data to the sfp port of the computer which are bonded together on a different subnet along with the OS0s. The OS0s, OS2, ethernet computer port, sfp computer ports each have a 24 subnet mask which prevent them from sending data on a different port while the network switch has a 16 subnet mask which let's it detect both the different subnets.
In spite of all this, I am facing an  issue wherein if I'm seeing the PointCloud2 info on rviz, it starts fluctuating in maximum intensity as soon as more than 3 lidars are brought up using the ouster_ros. Till 3 lidars, I can see the pointclouds properly but from 4 onwards every lidar pointcloud exhibits this fluctuation. Could you please help me diagnose the cause of this?

FYI, I'm attaching the commands text which I'm running to give more clarity

Thanks,
Shubhankar 
[5lidars_on_vehicle_commands.txt](https://github.com/ouster-lidar/ouster_example/files/9277603/5lidars_on_vehicle_commands.txt)

**Comment by kairenw** [comment]
Hmm, so you're running five separate roslaunch commands all on the same computer? Probably you've made some modifications to the code to support multisensor with `ouster_ros`?

Can you send us a video of what that fluctuation in maximum intensity looks like in rviz? (And a video of what it looks like with only 2 or 3 sensors without it)?  You can attach those to a ticket at our customer support [here](https://ouster.atlassian.net/servicedesk/customer/portal/8)

I'm going to close this ticket now but feel free to re-open if you don't get some response from us within a day or two.
