### ISSUE TITLE
Possible Error in Point Cloud Computation

### ISSUE THREAD

**Issue by cjtaylor22** [ouster-lidar/ouster_example#42]
I was reading through the code and saw something that doesn't seem to match up to the Software User Guide . Specifically in the make_xyz_lut function in the os1_util.cpp file. The computation of the normal vectors involves a variable called h_angle. When this is computed the line of code computes the sine of the relevant beam_azimuth_angle. According to the documentation this sine is incorrect and the beam azimuth angle should just be added to h_angle_0 after conversion to radians. In this case since the angles are so small the difference between the angle and its sine is negligible but I thought I should confirm my understanding of the reconstruction equations.

**Comment by dgarbuzov** [comment]
Thanks for pointing this out! Looks like a copy-paste error that went unnoticed. Should be fixed in 4ce8e4f
