### ISSUE TITLE
Change the format of Ouster LiDAR

### ISSUE THREAD

**Issue by yulan0215** [ouster-lidar/ouster_example#423]
Hi:

Sorry for bothering you, recently I used the Ouster LiDAR driver from here: https://github.com/ouster-lidar/ouster_example

The problem was that I would like to change the format of 3D point cloud with: XYZIR format, is there any method to change it based on: https://github.com/ouster-lidar/ouster_example

Thx

**Comment by kairenw** [comment]
Actually, we're talking in another ticket already: https://github.com/ouster-lidar/ouster_example/issues/419 Possibly you meant to post on the other repo? Closing as duplicate.
