### ISSUE TITLE
a lot of data is lost in the recorded rosbag

### ISSUE THREAD

**Issue by txyxy** [ouster-lidar/ouster_example#428]
Hi, we recorded the messages published from the ros node. After recording we checked the rosbag and found there are a lot of data lost. We checked the ethernet port transmission rate, it's 1000Mb/s. We used another network cable and got the same result. Could you give me some suggestions to fix this issue?

![lADPJxRxSukFEkrM280HgA_1920_219 jpg_620x10000q90g](https://user-images.githubusercontent.com/31716481/188104985-ecea12ea-e3f5-40b7-8a2a-d927ae3b3b61.jpg)

**Comment by Samahu** [comment]
This definitely looks unhealthy recording. Here is what typically things should look like:
![image](https://user-images.githubusercontent.com/606033/188170355-56cb7f4e-53ff-452e-8ca1-d572ad679799.png)

* Are you connected directly to the sensor or via a switch?
* Do you have other devices that might be transmitting data to same machine
* In case you have a firewall, disable temporarily and re-try the recording

**Comment by Samahu** [comment]
Two other thoughts:

* What firmware is your sensor on? consider upgrading to latest in case you are not.
* Check for any active alerts sensor from the sensor diagnostics page

**Comment by Samahu** [comment]
No response so far, closing this issue. Let us know if you are still having issues

**Comment by txyxy** [comment]
Thank you for your professional advicese and sorry to reply you so late. We still have problems with recording ros messages. For example, after we extracted msgs from the recorded imu rosbag, we found some thing strage like below:
![1667473446781_1DDF2B2D-7896-42e2-860A-D33C8D843257](https://user-images.githubusercontent.com/31716481/199714380-27b2caf3-e487-412d-86b1-3fbf374cfea0.png)
![1667474415186_A4CCBBDA-6014-4db9-AD4B-903452CDA9D6](https://user-images.githubusercontent.com/31716481/199714406-9943babe-49c3-42be-a5cf-a08ce075d2c5.png)

The timestamp of messages are confused. For example, message 19147 is sandwiched between messages 19127 and 19128. We  gusse that 19147 is a later one but got an advanced timestamp. We also gusse that 19147 is one of those "lost messages". 

We've been obsessed with this question for a long time so we plan to record in a different format. For recording data with unlimited duration, do you recommend using the python sdk to record data in pcap format? I see an example of pyhton, but it can only record 10 seconds of pcap data.

**Comment by Samahu** [comment]
You can increase the duration of recorded at this line:
https://github.com/ouster-lidar/ouster_example/blob/fa045e561600e4fd4227d0c95283f0d27e26f1e0/python/src/ouster/sdk/examples/client.py#L234

You can also modify the sample code to record until a certain condition is met.

**Comment by txyxy** [comment]
OK, I'll try it. Thanks!

**Comment by Samahu** [comment]
> OK, I'll try it. Thanks!

You are welcome.

Sorry I almost missed the other part of your questions

>The timestamp of messages are confused. For example, message 19147 is sandwiched between messages 19127 and 19128. We gusse that 19147 is a later one but got an advanced timestamp. We also gusse that 19147 is one of those "lost messages".

We rely on UDP to transfer IMU messages. Unlike TPC, UDP does not guarantee delivery or order of delivered messages. So messages coming out of order is expected. It should be possible however to write some logic to re-order messages by time or sequence number (within a specific window of time) or drop packets that are older than the last one received. We do some of that when assemble the lidar scan frame. Hope this helps!
