### ISSUE TITLE
Connecting Issue with New Ouster os1-xxxxxxxxxx

### ISSUE THREAD

**Issue by HappySamuel** [ouster-lidar/ouster_example#43]
Hi,

I just received the ouster 3D-lidar os1-16A. I connected the lidar to the Industrial PC, which come along with built-in 6 ethernet ports. I plugged the os1 into the IPC, but i couldn't run the os1 with ROS. I read the software manual, but still failed to get it hooked up.

Inside the software manual, it's written:
The sensor is configured to dynamically obtain an IP address using a DHCP server. If the
sensor is plugged into a network switch, it will automatically obtain an IP and you can find that
IP by checking the DNS leases on the network switch

Network setup:
ethernet is set to manual ip address: 192.168.1.1

ROS Launch file setup:
os1_hostname: os1-xxxxxxxxxxxx.local
os1_udp_dest: 192.168.1.1

but i couldn't find the ip_address of the sensors, therefore i try use the hostname, instead of using ip-address.

Besides, I tried to enter the following command into terminal:
nc os1-xxxxxxxxxxxx.local 7501
but i get nothing in return.

Therefore, I need some guides on how to hook it up or how to identify the sensor ip-address.

Samuel

**Comment by paxmaniac** [comment]
Did you install a DNS server on your machine (dnsmasq)? The instructions for this are in thee software manual.

**Comment by HappySamuel** [comment]
Hi, @paxmaniac 

Sorry for the late reply. I finally addressed the connection problem between ouster OS-1 and either direct to PC or through network switch/router. It's done according what you mentioned by following the software manual carefully. Thank you.

Samuel

**Comment by dkeeton2018** [comment]
@HappySamuel I'm coming across a similar issue and have followed the guide instructions with no luck. Did you ever have a failure to connect with the client IP?
Failed to connect to client at: 192.168.0.1
I keep getting this error and curious if you came across it and how you solved. Thank you.

**Comment by HappySamuel** [comment]
Hi @dkeeton2018 

First, is your ouster lidar connected directly to your pc or via a router/switch  ??
Second, What is the ip-address of your pc, and ip-address of your lidar  ??
Third, has you tried with the command: nc os1-xxxxxxxxxxxx 7501   ??

Best Regards,
Samuel

**Comment by dkeeton2018** [comment]
Thanks, I was able to solve on Sunday.

**Comment by HappySamuel** [comment]
Hi @antithing 

If you received your lidar recently, which mean it comes along with firmware 1.12. Then it should be easy.

First, you can set your ethernet connection to become manual and assign ip-address and netmask, and gateway too. Example as below picture:

![Screenshot from 2019-06-12 16-09-43](https://user-images.githubusercontent.com/18137963/59334222-933f7e00-8d2c-11e9-8424-37e95270edc3.png)

Second, you open your os1.launch and edit the os1_hostname to be os1-xxxxxxxx.local, together with os1_udp_dest to be the ip-address you set for the manual ethernet connection.

![Screenshot from 2019-06-12 16-11-42](https://user-images.githubusercontent.com/18137963/59334328-d26dcf00-8d2c-11e9-9008-42ea03be2e9d.png)

Then, it shall be done by now. save and try to run the launch file again.

Best,
Samuel

**Comment by antithing** [comment]
Thank you! I am on windows, without ros, I can ping the os1 using the serial, but i need the actual IP. 


is there a way to get the IP somehow?

thanks!

**Comment by HappySamuel** [comment]
Hi @antithing 

Since you are using it on windows, i couldn't help. Maybe you need to refer to the software manual. Or send email to Ouster and ask help from their technician.

Best,
Samuel

**Comment by JimmyFroost** [comment]
Hello @antithing,

I am trying to make it work on Windows as well.
Have you been successfull since last June ?

**Comment by antithing** [comment]
Hi @JimmyFroost, no unfortunately I had to give up on this hardware, as we were unable to get the data streaming in windows. Good luck! If you do solve it, please post it here!

**Comment by dsb6063** [comment]
Hi @JimmyFroost <https://github.com/JimmyFroost> ,

 

You may want to consider outsourcing. If you are an individual, try a kickstarter if there is enough interest in this particular problem. The developers at Kitware have already solved this issue. Kitware developed the Ouster Studio Software. I say a kickstarter since many developers on the forum have the same issues who would like to contribute. With a few kickstarter projects generating enough income to fund these issues. I have a business but little time. I have to use outside help for these tougher issues.  

 

Don’t give up. Just change the path. Good Luck!

**Comment by JimmyFroost** [comment]
So far, I can only view a "map" of lidar data through OusterStudio on windows :

![image](https://user-images.githubusercontent.com/50022505/70715406-8525e680-1cea-11ea-9ad9-ca10ac592fea.png)

Then, even if I have a target ip for lidar and IMU data, I am struggling with DNS mask, DHCP server, which I don't get at all...

![image](https://user-images.githubusercontent.com/50022505/70715444-9a9b1080-1cea-11ea-895b-b5910d3fc6b0.png)
