### ISSUE TITLE
How can I get timestamp and ambient from sensor_msgs::PointCloud2 ?

### ISSUE THREAD

**Issue by bigbigpark** [ouster-lidar/ouster_example#430]
Hi, I have a bag file including lidar point cloud data as a format of `sensor_msgs::PointCloud2`. <br/>
When I print the property of the message,  <br/>
![image](https://user-images.githubusercontent.com/72936863/190087212-8d6f9ce2-71ee-4e42-985c-ce3a74edd228.png)

<br/>
It contains 9 fields, [x, y, z, intensity, t, reflectivity, ring, noise, range]. <br/>
How can I access easily to `t`, `reflectivity`, `ring` like using a converter..! <br/>
I haven't found any conversion code. <br/>

**Comment by Samahu** [comment]
I believe that the `img_node.cpp` or `os_image_nodelet.cpp` (depending on which version of the SDK you have) do provide good example on how to consume these fields (if you are using C++) to handle the message. Search for the invocation `pcl::fromROSMsg`.

**Comment by bigbigpark** [comment]
Thanks
