### ISSUE TITLE
Serialization SensorInfo

### ISSUE THREAD

**Issue by d33dler** [ouster-lidar/ouster_example#431]
Greetings, I'm trying to pickle a Sensor() object by using multiprocessing.Pool() functionality to evaluate recordings in parallel, but it fails because SensorInfo object can't be pickled.

**Comment by kairenw** [comment]
Hi @d33dler,

Think you might have to add to the bindings yourself, with something like this: https://pybind11.readthedocs.io/en/latest/advanced/classes.html#pickling-support

**Comment by kairenw** [comment]
To do a development build of the Python SDK: https://static.ouster.dev/sdk-docs/python/devel.html

**Comment by d33dler** [comment]
Thank you!
