### ISSUE TITLE
Question about ouster lidar property

### ISSUE THREAD

**Issue by bigbigpark** [ouster-lidar/ouster_example#433]
Hi, I wonder where is the code that computes `reflectivity`, `noise` and `ring`. <br/>

Could you tell me which `.cpp` file doing this job? <br/>

Thanks.

**Comment by bigbigpark** [comment]
I solved this problem.

**Comment by juanluishortelano** [comment]
Could you write here where did you find them for future reference? Thanks

**Comment by bigbigpark** [comment]
Hi, you can find them by running ROS example with a bag file.

Point cloud from Ouster lidar has the mentioned properties.

I hope this will be helpful.

**Comment by juanluishortelano** [comment]
It is helpful but did you find the .cpp file that computes reflectivity?

**Comment by Samahu** [comment]
@juanluishortelano the SDK does not compute reflectivity, it comes directly from the sensor. You can refer to [this previous issue](https://github.com/ouster-lidar/ouster_example/issues/412) which mentions given an approximate answer to how reflectivity is computed.

**Comment by juanluishortelano** [comment]
Thanks, that is very interesting. My question was actually spawned by reading your answer in that issue. 

My confusion comes from the fact that intensity is the actual measurement that the sensor takes, if reflectivity also comes from the sensor through UDP: does that mean that the calculation reflectivity = cte * intensity * range^2 is done in the sensor itself? Does it not send the raw intensity value then?

**Comment by Samahu** [comment]
It does, it is basically what we now refer to as the SIGNAL.

**Comment by juanluishortelano** [comment]
Great, thank you for your answers!
