### ISSUE TITLE
Any Gazebo URDF Model provided?

### ISSUE THREAD

**Issue by HappySamuel** [ouster-lidar/ouster_example#44]
Hi Ouster,

Is there any URDF model provided for gazebo simulation???

Best Regards,
Samuel

**Comment by dgarbuzov** [comment]
Unfortunately no, though we welcome contributions!

**Comment by wilselby** [comment]
Try [this](https://github.com/wilselby/ouster_example/blob/master/ouster_description/urdf/OS1-64.urdf.xacro):

**Comment by HappySamuel** [comment]
Hi @wilselby 

Thank you very much for it. I will test it out soon.

Best,
Samuel

**Comment by HappySamuel** [comment]
Hi @wilselby 

I tried but i can only see your ouster os-1-64 model in RVIZ, there's no model in Gazebo. Do you know how i can visualize its model in Gazebo too?

Best,
Samuel

**Comment by wilselby** [comment]
I had it working on ROS kinetic and the associated Gazebo version but it may have issues on more recent versions of Gazebo (though I'm not sure why).  Let me know if you find out and I'll post here if I get around to integrating with Gazebo 9.

**Comment by HappySamuel** [comment]
Hi @wilselby 

I am using the Gazebo 9. I will update you too if i found a solution on this.

Best,
Samuel

**Comment by wilselby** [comment]
@HappySamuel I uploaded a new .dae file that works in Gazebo 9.

**Comment by HappySamuel** [comment]
Hi @wilselby 

Thanks for the update. It looks really nice.

Best,
Samuel
