### ISSUE TITLE
Failed to initialize sensor on Ubuntu 18.04

### ISSUE THREAD

**Issue by andressaff** [ouster-lidar/ouster_example#442]
Hi everyone,

I'm trying to connect sensor os0-32 on ubuntu 18.04 with ros Melodic. I'm using the FW 2.4, but when I initialize for roslaunch ouster_ros sensor.launch sensor_hostname:="os-122137000149.local" I get this log.

autaza-rafael-cintra@autaza-rafael-cintra:~/ouster $roslaunch ouster_ros sensor.launch sensor_hostname:="os-122137000149.local"
... logging to /home/autaza-rafael-cintra/.ros/log/074fd2b6-4e29-11ed-940c-541379ed11df/roslaunch-autaza-rafael-cintra-18026.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://autaza-rafael-cintra:34213/

SUMMARY
========

PARAMETERS
 * /ouster/os_cloud_node/tf_prefix: 
 * /ouster/os_cloud_node/timestamp_mode: 
 * /ouster/os_node/imu_port: 0
 * /ouster/os_node/lidar_mode: 
 * /ouster/os_node/lidar_port: 0
 * /ouster/os_node/metadata: 
 * /ouster/os_node/sensor_hostname: os-122137000149.l...
 * /ouster/os_node/timestamp_mode: 
 * /ouster/os_node/udp_dest: 
 * /ouster/os_node/udp_profile_lidar: 
 * /rosdistro: melodic
 * /rosversion: 1.14.13

NODES
  /
    relay_imu (topic_tools/relay)
    relay_lidar (topic_tools/relay)
    rviz (rviz/rviz)
  /ouster/
    img_node (nodelet/nodelet)
    os_cloud_node (nodelet/nodelet)
    os_node (nodelet/nodelet)
    os_nodelet_mgr (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [18039]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 074fd2b6-4e29-11ed-940c-541379ed11df
process[rosout-1]: started with pid [18055]
started core service [/rosout]
process[ouster/os_nodelet_mgr-2]: started with pid [18064]
process[ouster/os_node-3]: started with pid [18074]
process[ouster/os_cloud_node-4]: started with pid [18076]
process[ouster/img_node-5]: started with pid [18078]
process[rviz-6]: started with pid [18080]
process[relay_lidar-7]: started with pid [18082]
process[relay_imu-8]: started with pid [18083]
[ INFO] [1666017367.196913134]: Initializing nodelet with 4 worker threads.
[ INFO] [1666017368.179133165]: Loading nodelet /ouster/os_node of type nodelets_os/OusterSensor to manager os_nodelet_mgr with the following remappings:
[ INFO] [1666017368.214909967]: Will use automatic UDP destination
[ WARN] [1666017368.553711874]: Sensor os-122137000149.local configured successfully
[ INFO] [1666017368.553842611]: Starting sensor os-122137000149.local initialization...
[ INFO] [1666017369.200707682]: Loading nodelet /ouster/os_cloud_node of type nodelets_os/OusterCloud to manager os_nodelet_mgr with the following remappings:
[ INFO] [1666017369.209727252]: Loading nodelet /ouster/img_node of type nodelets_os/OusterImage to manager os_nodelet_mgr with the following remappings:
[ INFO] [1666017370.273791161]: rviz version 1.13.29
[ INFO] [1666017370.273829882]: compiled against Qt version 5.9.5
[ INFO] [1666017370.273838577]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1666017370.277791806]: Forcing OpenGl version 0.
[ INFO] [1666017370.564427058]: Stereo is NOT SUPPORTED
[ INFO] [1666017370.564485711]: OpenGL device: Mesa DRI Intel(R) HD Graphics 620 (KBL GT2)
[ INFO] [1666017370.564518480]: OpenGl version: 3,0 (GLSL 1,3).
[ WARN] [1666017386.876581308]: Client version: 0.5.2+unknown-release
[ WARN] [1666017386.876702613]: Using lidar_mode: 1024x10
[ WARN] [1666017386.876759715]: OS-0-32-U2 sn: 122137000149 firmware rev: v2.4.0
[ WARN] [1666017386.882023698]: No metadata file was specified, using: os-122137000149-metadata.json
[ INFO] [1666017386.882656279]: Wrote metadata to os-122137000149-metadata.json
[ INFO] [1666017386.886212925]: get_metadata service created
[ INFO] [1666017386.890585917]: get_config service created
[ INFO] [1666017386.894482520]: set_config service created
[ INFO] [1666017386.941911899]: OusterCloud: retrieved sensor metadata!
[ INFO] [1666017386.943138326]: Profile has 1 return(s)
[ INFO] [1666017387.022905185]: OusterImage: retrieved sensor metadata!
/opt/ros/melodic/lib/nodelet/nodelet: symbol lookup error: /home/autaza-rafael-cintra/ouster/devel/lib/libouster_ros.so: undefined symbol: _ZNK6ouster9LidarScan5fieldIjLj0EEEN5Eigen3RefIKNS2_5ArrayIT_Lin1ELin1ELi1ELin1ELin1EEELi0ENS2_8internal11conditionalIXsrS7_21IsVectorAtCompileTimeENS2_11InnerStrideILi1EEENS2_11OuterStrideILin1EEEE4typeEEENS_6sensor9ChanFieldE
================================================================================REQUIRED process [ouster/os_nodelet_mgr-2] has died!
process has died [pid 18064, exit code 127, cmd bash -c sleep 2; $0 $@ /opt/ros/melodic/lib/nodelet/nodelet manager __name:=os_nodelet_mgr __log:=/home/autaza-rafael-cintra/.ros/log/074fd2b6-4e29-11ed-940c-541379ed11df/ouster-os_nodelet_mgr-2.log].
log file: /home/autaza-rafael-cintra/.ros/log/074fd2b6-4e29-11ed-940c-541379ed11df/ouster-os_nodelet_mgr-2*.log
Initiating shutdown!
================================================================================
[relay_imu-8] killing on exit
[relay_lidar-7] killing on exit
[rviz-6] killing on exit
[ouster/os_cloud_node-4] killing on exit
[ouster/img_node-5] killing on exit
[ INFO] [1666017387.190951734]: Unloading nodelet /ouster/os_cloud_node from manager os_nodelet_mgr
[ INFO] [1666017387.191231027]: Unloading nodelet /ouster/img_node from manager os_nodelet_mgr
[ INFO] [1666017387.192214572]: waitForService: Service [/ouster/os_nodelet_mgr/unload_nodelet] could not connect to host [autaza-rafael-cintra:51119], waiting...
[ WARN] [1666017387.192343674]: Couldn't find service os_nodelet_mgr/unload_nodelet, perhaps the manager is already shut down
[ INFO] [1666017387.193466359]: waitForService: Service [/ouster/os_nodelet_mgr/unload_nodelet] could not connect to host [autaza-rafael-cintra:51119], waiting...
[ WARN] [1666017387.193501319]: Couldn't find service os_nodelet_mgr/unload_nodelet, perhaps the manager is already shut down
[ouster/os_node-3] killing on exit
[ouster/os_nodelet_mgr-2] killing on exit
[ INFO] [1666017387.194916525]: Unloading nodelet /ouster/os_node from manager os_nodelet_mgr
[ INFO] [1666017387.195900891]: waitForService: Service [/ouster/os_nodelet_mgr/unload_nodelet] could not connect to host [autaza-rafael-cintra:51119], waiting...
[ WARN] [1666017387.195928567]: Couldn't find service os_nodelet_mgr/unload_nodelet, perhaps the manager is already shut down
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by Samahu** [comment]
Do you have eigen library installed? which version?
```bash
dpkg -l | grep eigen # should list the version of eigen library
```

**Comment by andressaff** [comment]
I have eigen library installed, the version is 3.3.4 @Samahu 

dpkg -l | grep eigen

ii  libarpack2:amd64                             3.5.0+real-2                                    amd64        Fortran77 subroutines to solve large scale eigenvalue problems
ii  libarpack2-dev:amd64                         3.5.0+real-2                                    amd64        Fortran77 subroutines to solve large scale eigenvalue problems (development)
ii  libeigen3-dev                                3.3.4-4                                         all          lightweight C++ template library for linear algebra
ii  ros-melodic-eigen-conversions                1.12.1-1bionic.20210505.012246                  amd64        Conversion functions between: - Eigen and KDL - Eigen and geometry_msgs.
ii  ros-melodic-tf2-eigen                        0.6.5-0bionic.20210505.012921                   amd64        tf2_eigen

**Comment by Samahu** [comment]
@andressaff I don't see a particular problem with you installation, I am trying to produce the problem locally and will get back to you soon.

**Comment by andressaff** [comment]
@Samahu thank you, I am waiting for your answer =)

**Comment by Samahu** [comment]
I couldn't re-produce the issue locally, so I do suspect that you have some sort of conflict in your setup. 

What is your gcc/compiler version?
what command did you use to compile the ouster-ros driver? Did you perform a clean build (if not could you re-try)?
Do you have **tbb** installed?

**Comment by andressaff** [comment]
- The gcc version is gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
- I used catkin_make --cmake-args -DCMAKE_BUILD_TYPE=Release
- I have tbb installed
ii  libtbb-dev:amd64                             2017~U7-8                                       amd64        parallelism library for C++ - development files
ii  libtbb2:amd64                                2017~U7-8                                       amd64        parallelism library for C++ - runtime files

**Comment by Samahu** [comment]
> * The gcc version is gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
> * I used catkin_make --cmake-args -DCMAKE_BUILD_TYPE=Release
> * I have tbb installed
> 
> ```
> ii  libtbb-dev:amd64                             2017~U7-8                                       amd64        parallelism library for C++ - development files
> ii  libtbb2:amd64                                2017~U7-8                                       amd64        parallelism library for C++ - runtime files
> ```

Ok, I have seen some posts around indicating that **tbb** may cause some conflict with **eigen**. Could you try totally removing tbb and recompiling (clean build)?

**Comment by Samahu** [comment]
> I totally removing tbb and recompiling used catkin_make --cmake-args -DCMAKE_BUILD_TYPE=Release, but I had the same error.

I am not able to produce the problem you reported on a fresh ubuntu:18.04 setup. I used docker of course.
Did you perform a clean build (which means deleting build/devel/install folders from your catkin workspace)?
I do highly suspect that **tbb** to be the issue but it could be something else on your system. also when compiling please make sure you start a new command prompt after you have removed **tbb**.

If what I have suggested does not work, is docker an option that you could use?

**Comment by andressaff** [comment]
@Samahu I managed to use ouster ros with ubuntu 18.04 and ros melodic. I believe the problem was my computer, but I changed of computer now.
