### ISSUE TITLE
Ouster not shutting off at max temperature 

### ISSUE THREAD

**Issue by ZeeshanshariffNS** [ouster-lidar/ouster_example#467]
Hi, I'm using HTTP server to query ouster temperature, i see that the temperature is 80 degrees but as mentioned in the ouster manual, the max shutdown temperature is 60/65 degrees but it still publishes ouster data in spite of being running beyond maximum temperature.
![ouster](https://user-images.githubusercontent.com/119054421/207279254-546ac7d6-a80a-4724-8649-7be2814db7a4.png)

Is there a way to enable maximum shutdown temperature?

secondly, so how accurate is the data from HTTP. is it up to some
 decimal value. for example: i see that at start the input voltage is 55 degree with 11.353 V, while at 81 degrees it is 11.430 V.

Also is there a way to track temperature before it reaches the max shutdown temperature, which can give some indications for the same.

**Comment by kairenw** [comment]
Hi - I'm going to send you to our[ Sensor Support](https://ouster.atlassian.net/servicedesk/customer/portal/8) since on this GH we answer questions mostly pertaining the Ouster SDK. Thanks! 

If you don't get a response there, you can come back and let us know and we'll ping them.
