### ISSUE TITLE
Where can I find the Yolov5-LiDAR Repo?

### ISSUE THREAD

**Issue by Crear12** [ouster-lidar/ouster_example#474]
Hi Ouster Team,
I saw the "Object Detection and Tracking using Deep Learning and Ouster Python SDK". Is it available on GitHub?
https://ouster.com/blog/object-detection-and-tracking-using-deep-learning-and-ouster-python-sdk/

**Comment by kairenw** [comment]
Hi @Crear12,

I think you can find the example at on Fisher's GH here: https://github.com/fisher-jianyu-shi/yolov5_Ouster-lidar-example

Closing this out now
