### ISSUE TITLE
Trouble compiling the C++ sdk source

### ISSUE THREAD

**Issue by Perceval62** [ouster-lidar/ouster_example#482]
# What is going on
I followed the instructions on the documentation to build the examples.
I got to make a directory, cmake .. and then the cmake --build command fails with the given error.

![image](https://user-images.githubusercontent.com/31328738/216161109-637531bd-bad8-4e9e-9c5e-55ad83b4dd23.png)

Am I doing it right ?
am I supposed to compile the sdk and then use it ?

**Comment by Samahu** [comment]
what is your build structure is like?

Did you follow the build instructions as stated here https://static.ouster.dev/sdk-docs/cpp/building.html:
```bash
mkdir build
cd build
cmake  <path to ouster_example> -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=ON
cmake --build .
```

**Comment by Samahu** [comment]
I am not sure but I found that you build path has a space `ouster python` .. certain tools don't like that.

**Comment by Perceval62** [comment]
Oh, you're right. I'll try renaming the folder then.
But apart from that, I followed the instruction as stated in the document that you linked.
The build structure is a verbatim clone of the master branch.

**Comment by Samahu** [comment]
Closing the issue, let us know if you are still having build issues.

**Comment by Perceval62** [comment]
Fair enough,
I won't be near the lidar unit until tomorrow.
I'll poke y'all to let you know if removing the space is a fix
