### ISSUE TITLE
No support for udp_profile_lidar and udp_profile_imu from calls to parse_metadata()

### ISSUE THREAD

**Issue by MPeebles** [ouster-lidar/ouster_example#489]
I am trying to use the [ouster-ros (ros2-foxy)](https://github.com/ouster-lidar/ouster-ros/tree/ros2-foxy)  driver to operate a LiDAR in dual return mode. This repo is included as a submodule.

The driver makes a call to `ouster::sensor::parse_metadata()` to interpret JSON data provided from the LiDAR unit:
``` c++
sensor_info parse_metadata(const std::string& metadata) {
    Json::Value root{};
    Json::CharReaderBuilder builder{};
    std::string errors{};
    std::stringstream ss{metadata};

    if (metadata.size()) {
        if (!Json::parseFromStream(builder, ss, &root, &errors))
            throw std::runtime_error{errors};
    }

    sensor_info info{};
    if (is_new_format(metadata)) {
        logger().debug("parsing non-legacy metadata format");
        info = parse_legacy(convert_to_legacy(metadata));
    } else {
        logger().debug("parsing legacy metadata format");
        info = parse_legacy(metadata);
    }
    return info;
}
```

It appears that the subsequent calls to `ouster::sensor::convert_to_legacy()` and `ouster::sensor::parse_legacy()` do not support the "udp_profile_lidar" and "udp_profile_imu" fields, even though the underlying `ouster::sensor::data_format` struct does.

Is the lack of support for these fields intended?   

For now I have worked around this issue by including support to these fields in both `ouster::sensor::convert_to_legacy()`  and `ouster::sensor::parse_legacy()`.

[this](https://github.com/ouster-lidar/ouster-ros/issues/71) is a related issue for the `ouster-ros` driver repo

**Comment by kairenw** [comment]
I don't really understand what you mean by is not supported. 

In `convert_legacy()` the following line should copy over every key within the `data_format` struct. 
https://github.com/ouster-lidar/ouster_example/blob/cdc5605570c1e1a3c28a9bde043c2fb8ba2bdcac/ouster_client/src/types.cpp#L1006-L1009

Simlarly, `parse_legacy()` parses the `udp_profile_lidar`:
https://github.com/ouster-lidar/ouster_example/blob/cdc5605570c1e1a3c28a9bde043c2fb8ba2bdcac/ouster_client/src/types.cpp#L751
