### ISSUE TITLE
Where are the GPS values? 

### ISSUE THREAD

**Issue by laurent82** [ouster-lidar/ouster_example#491]
Hello, 

I am new to the SDK and Ouster products so I may have missed some information.

I synchronized the lidar and the GPS according to the guide and I have the "locked" values on 1 as well as the "last_read_message"  values seem correct.

But that's just using the HTTP API. I can't find these values anywhere in the Python or C++ SDK. I thought there would be a field in the LidarScan class or possibly LidarPacket or ImuPacket. So I have no idea how to link the scans to the GPS values.

How should it be done?
Thanks

**Comment by kairenw** [comment]
Apologies. Thanks for opening the issue. That's correct - no GPS comes to the SDK from the UDP packet, and we don't currently support polling and matching the GPS to scans, so you'd have to handle it yourself. 

I recommend contacting your sales representative to ask for this feature to be prioritized. I will keep this open, however.

**Comment by mos-ali** [comment]
@kairenw 
is that means , i must add GPS device to get the GPS data , as no GPS data coming from the Lidar device ...?

**Comment by kairenw** [comment]
Hi @mos-ali that's correct. I'd encourage you to contact your FAE or [ouster sensor support](https://ouster.atlassian.net/servicedesk/customer/portal/8/group/22/create/86) if you have questions about how to set it up.
