### ISSUE TITLE
ouster.client.core.ClientTimeout: No packets received within 2.0s

### ISSUE THREAD

**Issue by will22thomas** [ouster-lidar/ouster_example#495]
I have an OS-0 LiDAR that I am trying to use with python. Most of the time it works fantastic. I can stream and run the example code just fine. However, I've noticed after a while of testing code, I start getting this error:

ouster.client.core.ClientTimeout: No packets received within 2.0s

I've tried a number of solutions, sometimes they fix the problem and sometimes they don't. It seems pretty inconsistent. I have unplugged the lidar from the wall, and the computer, I've re-configured it, and reset the UDP destination address. Often times I do a combination of these things, and sometimes it eventually works, but not always.
Any ideas?

**Comment by kairenw** [comment]
Thanks for opening the new ticket!

So that error is a catch all - if anything is messed up in the networking that will appear. 

When you say example code, what are you running exactly? That will help me out a bit? Also when you can't access it, generally can you ping the sensor and do you check the ports and udp_dest?

**Comment by will22thomas** [comment]
I guess a lot of what I'm running is the example code. I've written some of my own code too, and when it throws this error, I try to run the live_plot_reflectivity() function to see if it's my code causing the error or something else. When it's not receiving packets, I can still ping its ip address. I also reset the udp_dest by removing its configuration and resetting it to the local address. 
![image](https://user-images.githubusercontent.com/77360183/225358814-9db879fe-6c15-468d-a1da-fbfdb550a28c.png)


This is the error I'm getting in the terminal, it seems to just be a timeout, but I'm not sure where it's coming from.
![image](https://user-images.githubusercontent.com/77360183/225359581-77b469b8-a9e3-4758-b7f8-4eb487575ab6.png)

**Comment by kairenw** [comment]
hey @will22thomas did you get this resolved?

**Comment by Flatliu** [comment]
Hi @kairenw , I got the same thing when running " simple-viz --sensor <SENSOR_HOSTNAME>". I tried ping the sensor, and receive the message below, does it mean my laptop could receive the message from sensor? The screenshot of the configuration tab is below. What should I do next?
<img width="1224" alt="Screen Shot 2023-06-19 at 18 52 24" src="https://github.com/ouster-lidar/ouster_example/assets/48779470/d7b94c3f-156a-4745-9b0c-16f4ca0ec97a">
<img width="1168" alt="Screen Shot 2023-06-19 at 18 52 43" src="https://github.com/ouster-lidar/ouster_example/assets/48779470/27f143fe-03f2-4566-95c7-d321f88499ac">

**Comment by kairenw** [comment]
Hi @Flatliu, please open a new issue. That makes it a bit easier to make sure that you and will22thomas seprately get resolutions as needed

Have you checked your firewall?

**Comment by kairenw** [comment]
Closing with no response. Flatliu, please open a new ticket if you still need support
