### ISSUE TITLE
output of the signal image is quite bad

### ISSUE THREAD

**Issue by gauravkuppa** [ouster-lidar/ouster_example#504]
**Describe the bug**
The output of the signal image is quite bad. It is far too noisy, and it seems to be caused by the library. When I extract the signal image from the OS-1-32 LiDAR itself (through ROS2), I get very nice signal images. When I use the Python SDK, as shown below, the results are bad. For reference, the results are bad even for the sample data from the Ouster website, regardless of the resolution (32, 64, 128 beams).

**To Reproduce**
```
pcap_file = pcap.Pcap(source, metadata)
with closing(client.Scans(pcap_file)) as scans:
    for scan in scans:
        field = scan.field(client.ChanField.SIGNAL)
        val = client.destagger(pcap_file.metadata, field)
        img = val.astype(np.uint8)
        cv2.imwrite("signal.png"), img)
```
**Screenshots**
Signal Image from Python SDK
![img0001](https://user-images.githubusercontent.com/24405632/230617550-befeaa02-4cda-486b-911a-c5d9f266a5b3.jpg)

Signal Image from ROS 2 Ouster Driver
![00000](https://user-images.githubusercontent.com/24405632/230617714-545592a4-5aa5-4f38-b09d-520df82e3623.jpg)

**Platform (please complete the following information):**
- Ouster Sensor? OS-1-32
- Ouster Firmware Version? v2.4.0
- Programming Language? Python 3.8
  - For Python include the targeted Python version
- Operating System? Ubuntu
- Machine Architecture? x86

**Comment by kairenw** [comment]
I think the casting is creating some artifacts. For ex:

```
cv2.imwrite("signal_cast.png", np.uint8(val))
cv2.imwrite("signal_clip_then_cast.png", np.uint8(np.clip(val, 0, 255)))
```

gives signal_cast:
![signal_cast](https://user-images.githubusercontent.com/44489146/230654353-e3efb48a-4726-4bc5-9771-eba0e24e8aea.png)
and signal_clip_then_cast:
![signal_clip_then_cast](https://user-images.githubusercontent.com/44489146/230654357-dbdaf96c-6fa4-4b05-811e-c00643fa4f35.png)

**Comment by Samahu** [comment]
@gauravkuppa we have recently updated and re-published the tutorial that shows how to perform Object Detection and Classification using YOLOv5 against Lidar Data generated by Ouster sensors, the tutorial(s) can be found here: https://github.com/ouster-lidar/ouster-yolov5-demo. If you read through the provided [Jupyter notebook](https://github.com/ouster-lidar/ouster-yolov5-demo/blob/main/Ouster_Yolo5_Demo.ipynb) it explains the auto leveling concept that @kairenw hinted at and how the **AutoExposure** should be applied to the `SIGNAL` channel before performing passing it to the YOLOv5 model for inference. The tutorial performs inference on the 4 channels and shows the result of each channel next to each other (`SIGNAL` is the 2nd row):
![image](https://user-images.githubusercontent.com/606033/236242386-39a0f630-28a3-4cbd-a2a4-65fb240111f2.png)

**Comment by kairenw** [comment]
Closing as we have answered the question in multiple ways. Please reopen if you have more questions.
