### ISSUE TITLE
how to add a pull-up resistor with interface box to get 3.3V

### ISSUE THREAD

**Issue by zhiranyan** [ouster-lidar/ouster_example#506]
**Describe your question**
A clear and concise description of your question.

Hello, according hardware manual I need one pull-up resistor to amplify the MULTIPURPOSE_IO voltage. Now I have set this pin as OUTPUT mode. I have connected this pin and GND pin with another camera via two jumper cables. How to add the resistor in the circuit? Could you provide more details about this? 

Thanks a lot.

**Screenshots**

**Platform (please complete the following information):**
- Ouster Sensor? \OS-1
- Ouster Firmware Version? \[e.g. 2.3, 2.4, ..\]
- Programming Language? \[e.g. C++, Python, ..\]
  - For Python include the targeted Python version
- Operating System? \ Ubuntu 
- Machine Architecture? \ x64
- git commit hash (if not the latest).

**Comment by kairenw** [comment]
Hi @zhiranyan,

I recommend contacting [our technical customer sensor support,](https://ouster.atlassian.net/servicedesk/customer/portal/8) as this Github exists to address questions about the Ouster SDK. I'll keep this issue open for now and you can let me know if you don't hear back from our customer support.

**Comment by kairenw** [comment]
Closing - feel free to reopen if our technical customer sensor support hasn't replied!
