### ISSUE TITLE
Curiosity about LiDAR noise difference depending on distance

### ISSUE THREAD

**Issue by KangHyunwoogi** [ouster-lidar/ouster_example#510]
I wonder if LiDAR sensor increases their uncertainty with increasing distance.

If so, I would appreciate it if you could tell us about any additional evidence you can obtain in this regard.

Thank you.

**Comment by kairenw** [comment]
Hi @KangHyunwoogi,

Thanks for reaching out. This Github is for the Sensor SDK, whereas you question is a question for our sensor support. I would try writing to your Ouster contact or contacting our technical support [here](https://ouster.atlassian.net/servicedesk/customer/portal/8/group/22/create/86)

I'll close this issue now, but feel free to re-open if you don't get a response in a few days from that portal.
