### ISSUE TITLE
Calibrated extrinsic parameter

### ISSUE THREAD

**Issue by tjiangpeng** [ouster-lidar/ouster_example#52]
Could you provide the calibration result of the lidar configuration? Namely the yaw, roll, pitch angle of the lidar frame relative to the vehicle frame.
The extrinsic parameter would be useful for our test on the ouster lidar data. Thanks a lot.

**Comment by dllu** [comment]
Do you mean for the sample data? The extrinsic calibration may be different depending on how you install it. The vehicle frame is arbitrary in any case.

**Comment by tjiangpeng** [comment]
Yes, I mean for the 11 rosbag samples. When I visualized the sample point cloud, I found the road plane is not horizontal, which means your lidar is mounted with a tilt angle. You are right, the vehicle frame can be arbitrary. The vehicle frame I mean, is defined with x-y plane parallel to vehicle base plate, forward x, left y, z axis vertical to x-y plane. 
My research group are trying to equip ouster OS-1 lidar into our vehicle, but I want to verify my algorithm on your sample data first. And the algorithm I design requires accurate calibration of the mounted angle. I am just wondering whether you calibrate the rotation angle of lidar frame relative to the vehicle frame I mean. If you did, it would be helpful to provide it.

**Comment by dllu** [comment]
You can probably fit a plane to the ground points, using, for example, RANSAC based plane fitting.

**Comment by mrgransky** [comment]
@tjiangpeng Did you guys also have GNSS/INS integrated to your OS1 ?
is your project opensource?

**Comment by dgarbuzov** [comment]
Sorry, don't think we have the calibration available at the moment
