### ISSUE TITLE
Python 3.11 wheels for ouster-sdk

### ISSUE THREAD

**Issue by scottEpicWin** [ouster-lidar/ouster_example#520]
**Describe the bug**
when attempting to install ouster-sdk via pip with ```python3.11 -m pip install ouster-sdk```
it returns
```ERROR: Could not build wheels for ouster-sdk, which is required to install pyproject.toml-based projects```
full error attached below

**To Reproduce**
on my windows 10 machine in powershell or a command prompt, i just run ```python3.11 -m pip install ouster-sdk```

**Platform (please complete the following information):**
- Ouster Sensor? OS-0-32-U
- Ouster Firmware Version? v2.5.1
- Programming Language?  python3.11
- Operating System? windows 10 pro
- Machine Architecture? x86_64

**Full Terminal Output**
[terminal.txt](https://github.com/ouster-lidar/ouster_example/files/11626516/terminal.txt)

**Comment by kairenw** [comment]
Python 3.11 wheels are now available via pypi
