### ISSUE TITLE
No packets received within 2.0s with DHCP over Router

### ISSUE THREAD

**Issue by Vkhark** [ouster-lidar/ouster_example#526]
**Describe the bug**
I cannot receive Scans through the SDK or simple-viz. I can view the Sensor-information in the code though (meta data). I always get the "No packets received within 2.0s" The visualization works in Ouster Studio sometimes though. (It worked for the OS-DOME in this configuration)
I have checked with netcat if I am receiving Data through the relevant ports. Data arrives but is not recognized by the Ouster SDK. It works without problems if I use static IPs or link local when directly connected to the sensors. 

**To Reproduce**
1. Connect Sensors to Router
2. Let Sensor get IP Adress from DHCP-Functionality
3. Set Correct Destination IP for sensor
4. Connect Computer to Router and get IP with DHCP 
5. Execute simple-viz => receive "No packets received within 2.0s"

**Screenshots**
![image](https://github.com/ouster-lidar/ouster_example/assets/6047900/ee6a06b9-0a7e-4acb-a0fc-bf0c46eb74ae)

Just 2 sensors I have currently connected to the Router: 
![image](https://github.com/ouster-lidar/ouster_example/assets/6047900/489bfb21-01cb-40b7-a293-4e266e367843)
![image](https://github.com/ouster-lidar/ouster_example/assets/6047900/72da42e7-c8b8-40da-ba70-451df52a238e)
also local IP 
![image](https://github.com/ouster-lidar/ouster_example/assets/6047900/d6d843f3-6ccc-4e36-973a-003a36bf3da7)

As you can see from above the sensors and the computer are all in the same Subnet. 

**Platform (please complete the following information):**
- Ouster Sensor?
- I have had this problem with every sensor. I tried OS-1, OS-Dome, OS-0 ....
- Ouster Firmware Version? \[e.g. 2.3, 2.4, ..\]
- ousteros-image-prod-bootes-v3.0.1+20230209044733
- Programming Language? \[e.g. C++, Python, ..\]
  - I am using Python 3.10.10 
- Operating System? \[e.g. Linux, Windows, MacOS\]
- I am using Windows 
- Machine Architecture? \[e.g. x64, arm\]
- x64

**Comment by Vkhark** [comment]
The prompt about the Python Version in the Bug-Reporting helped me. Downgraded to Python 3.9.16 and it worked!

**Comment by kairenw** [comment]
Hi @Vkhark -

I don't think I understand. Which Python were you using before? How would it resolve things?

**Comment by kairenw** [comment]
Closing with no response.

**Comment by Vkhark** [comment]
As stated above i was using Python 3.10.10?

Don't know about now but at that time I guess there was some compatibility problem. But anyway Python 3.9.16 was enough for me so I did not investigate further... as it worked without problems on Python 3.9.
