### ISSUE TITLE
IMU DATA in example

### ISSUE THREAD

**Issue by louis960126** [ouster-lidar/ouster_example#53]
Hi there, 
    I am going to buy an 128 beam OS-1 Lidar, Is it an IMU on-board? 
I just try the example from http://data.ouster.io/sample-data-1.12/index.html, but i can't read the imu data in rostopic echo. is there anything we need to fix in the program?  thx!

**Comment by dgarbuzov** [comment]
Thanks for pointing that out!  The sample data was missing imu output -- should be fixed now.

For questions about ouster products, please use https://www.ouster.io/contact
