### ISSUE TITLE
Alpha in the function of intensity and reflectivity

### ISSUE THREAD

**Issue by shadowwkl** [ouster-lidar/ouster_example#531]
May I ask what is the alpha value?

              The relation is shown by the following equation but it is merely an approximation:
$$reflectivity = α * intensity * range^2$$
Where $α$ is a constant

_Originally posted by @Samahu in https://github.com/ouster-lidar/ouster_example/issues/412#issuecomment-1208316001_

**Comment by kairenw** [comment]
We can't provide that, but you may find the following link in the sensor docs useful for using reflectivity: [reflectivity data mapping](https://static.ouster.dev/sensor-docs/image_route1/image_route2/sensor_data/sensor-data.html#reflectivity-data-mapping)
