### ISSUE TITLE
Unable to include #include "ouster/os_pcap.h" into new C++ files

### ISSUE THREAD

**Issue by arunumd** [ouster-lidar/ouster_example#539]
**Describe the bug**
The inclusion of **_#include "helpers.h"_** into new C++ files other than the _[representations_example.cpp](https://github.com/ouster-lidar/ouster_example/blob/master/examples/representations_example.cpp)_, leads to **_fatal error: ouster/os_pcap.h: No such file or directory_**

**To Reproduce**
Steps to reproduce the behavior (steps below are just an example):
1. Include the "helpers.h" file into client_example.cpp or any other cpp file like shown below in the screenshot on line#12
2. Compile the code
3. Run the code
4. observe the issue

**Screenshots**
![image](https://github.com/ouster-lidar/ouster_example/assets/32076623/996ee543-ce85-4c9c-a871-7701b1ff66ad)

**Platform (please complete the following information):**
- Ouster Sensor? \[OS-1]
- Ouster Firmware Version? \[2.5.1]
- Programming Language? \[C++]
- Operating System? \[e.g. Linux]
- Machine Architecture? \[x64]
- git commit hash (if not the latest).

**Comment by kairenw** [comment]
Hi Arun, 

I think you have to edit the CMakelists.txt appropriately. See the way representations_example is done in `examples/CMakelists.txt`
