### ISSUE TITLE
os1_udp_dest not found

### ISSUE THREAD

**Issue by hachbani2019** [ouster-lidar/ouster_example#54]
Hi, 

I'm encountring an issue on my first steps with an ouster Lidar. I did configure the hostname and the ip adress, while trying to launch the os1.launch launch file, I don't know what to set for os1_udp_dest, All what I know is that it's meant for the IP to which the sensor should send data. 
 
I type roslaunch `ouster_ros os1.launch os1_hostname:=os1-991832000916 lidar_mode:=1024x20` leaving the os1_udp_dest to its default value, the following messages appear on the terminal: 

```
[ WARN] [1557402637.766353346]: Lidar mode set in replay mode. May be ignored
[ INFO] [1557402637.766416738]: Running in replay mode
[ INFO] [1557402637.766433106]: Reading metadata from os1-991832000916.json
[ WARN] [1557402637.766484318]: Failed to read os1-991832000916.json; check that the path is valid
[ WARN] [1557402637.766556252]: Unknown sensor firmware version; output may not be reliable
[ WARN] [1557402637.766571925]: Lidar mode not found in metadata; output may not be reliable
[ WARN] [1557402637.766583399]: Beam angles not found in metadata; using design values
[ WARN] [1557402637.766598271]: Frame transforms not found in metadata; using design values
[ INFO] [1557402637.766618821]: Using lidar_mode: 1024x20
[ INFO] [1557402637.766632568]: Sensor sn: UNKNOWN firmware rev: UNKNOWN
```

I also try the same command using the Ouster Ip address and not the hostname, but still. 

Can anyone help me please?

Thanks !

**Comment by dllu** [comment]
It appears that you are running it in replay mode. If you are using a real lidar sensor, you may need to set `replay:=false`
