### ISSUE TITLE
wrong usage of curl command

### ISSUE THREAD

**Issue by zehranrgi** [ouster-lidar/ouster_example#546]
**Describe your question**
HI, I wrongly used the below command and I cannot reach my device anymore. Is there any reset or any way to fix it? 
Lidar is showed as not found. When I ping the lidar sn, there is nothing. 

`curl -i -X PUT http://os-our_number.local/api/v1/system/network/ipv4/override -H 'Content-Type: application/json' --data-raw '"if_config_number(ssh number of pc)/24`

**Screenshots**
![IMG_4042](https://github.com/ouster-lidar/ouster_example/assets/70450368/b21cc6b7-31d8-4660-924d-367d2df546c4)

![IMG_4062](https://github.com/ouster-lidar/ouster_example/assets/70450368/beb675bd-124e-4dd0-b4b8-449a1c0f4db6)

**Platform (please complete the following information):**
- Ouster Sensor? \[e.g. OS-0, OS-1, ..\]
- Ouster Firmware Version? \[e.g. 2.3, 2.4, ..\] LATEST
- Programming Language? \[e.g. C++, Python, ..\]
  - For Python include the targeted Python version
- Operating System? \[e.g. Linux, Windows, MacOS\]. : LINUX UBUNTU
- Machine Architecture? \[e.g. x64, arm\]. : X64 

THANKS for any kind of help! @twslankard

**Comment by twslankard** [comment]
Hello @zehranrgi, thanks for your question.

You mentioned you are unable to reach the device after running the curl command. Which way are you attempting to access the device - through a browser?

Cheers,
Tom Slankard
Staff Software Engineer
Ouster Inc.

**Comment by twslankard** [comment]
@zehranrgi

The curl command you ran should have set the static IP address of the device to the IP address you specified.

If you specified the same IP address as another device on your network (such as your PC) you may run into issues connecting to the sensor's web configuration GUI. (You may have to change your PC's IP address temporarily in this case.)

If the new IP address you specified is not the same as another device, you should be able to contact the device on this new IP address provided the address is within your router's configured subnet.

Please see the [sensor HTTP API reference](https://static.ouster.dev/sensor-docs/image_route1/image_route2/common_sections/API/http-api-v1.html) for more details.

Note, the static IP of the sensor may also be removable using this curl command:

`curl -i -X DELETE http://<sensor address>/api/v1/system/network/ipv4/override`

If you are still running into issues connecting to the sensor, please contact support@ouster.io.

**Comment by zehranrgi** [comment]
> @zehranrgi
> 
> The curl command you ran should have set the static IP address of the device to the IP address you specified.
> 
> If you specified the same IP address as another device on your network (such as your PC) you may run into issues connecting to the sensor's web configuration GUI. (You may have to change your PC's IP address temporarily in this case.)
> 
> If the new IP address you specified is not the same as another device, you should be able to contact the device on this new IP address provided the address is within your router's configured subnet.
> 
> Please see the [sensor HTTP API reference](https://static.ouster.dev/sensor-docs/image_route1/image_route2/common_sections/API/http-api-v1.html) for more details.
> 
> Note, the static IP of the sensor may also be removable using this curl command:
> 
> `curl -i -X DELETE http://<sensor address>/api/v1/system/network/ipv4/override`
> 
> If you are still running into issues connecting to the sensor, please contact [support@ouster.io](mailto:support@ouster.io).

It gave error with this delete command. It didnt run

**Comment by zehranrgi** [comment]
I connected the Ouster ethernet cable to another PC. Then, I reset the configuration.
