### ISSUE TITLE
os1_node.cpp crashing due to JSON error

### ISSUE THREAD

**Issue by tjblada** [ouster-lidar/ouster_example#55]
After updating Ubuntu 18.04, os1_node.cpp now gives a segfault when running the lidar code. Here is my stacktrace:

Starting program: /home/USER/rosdev/catkin_ws/devel/lib/ouster_ros/os1_node
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff71bb350 in ?? () from /usr/lib/x86_64-linux-gnu/libjsoncpp.so.1

**Comment by tjblada** [comment]
Spent a bit of time narrowing it down to Json::CharReaderBuilder builder{}; line in os1.cpp.

**Comment by dllu** [comment]
You may need to clean the build and recompile the project whenever you update your operating system.

[Ubuntu updates may cause ABI breaks](https://askubuntu.com/questions/249425/what-guarantees-does-ubuntu-provide-concerning-binary-compatibility-across-relea).
