### ISSUE TITLE
Upgrading from v1.13.0 to v2.4.0

### ISSUE THREAD

**Issue by EdvardSire** [ouster-lidar/ouster_example#555]
**Describe your question**
Hello, can you help me with updating from `ousteros-image-prod-aries-v1.13.0-20191105025459` to `ousteros-image-prod-aries-v2.4.0+20220921174636`.

This is the error I'm getting with chrome. I previously got "Unknown error" on both platforms using firefox. There was a problem with the POST request to the firmware endpoint.

**Screenshots**
![Screenshot 2023-09-25 at 19 47 09](https://github.com/ouster-lidar/ouster_example/assets/45853648/c8c906b0-6422-45b9-bcec-f76097d2ce08)

**Platform (please complete the following information):**
- Ouster Sensor? OS-1 rev5
- Ouster Firmware Version? prev
- Operating System? Have tried both `Darwin Kernel Version 22.5.0 arm64` and `5.15.0-84-generic 20.04.1-Ubuntu x86_64 GNU/Linux`
- git commit hash: na

**Comment by twslankard** [comment]
Thanks for your inquiry, @EdvardSire. This GitHub project is specific to ouster-sdk.

Please contact Ouster Customer Support here, who can help you with any issues related to Firmware upgrades:
https://ouster.atlassian.net/servicedesk/customer/portal/8/group/22/create/86

Best Regards,

Tom
Staff Engineer
Ouster Inc.

**Comment by goushi-zhang** [comment]
我也遇到了这个问题，请问如何解决
