### ISSUE TITLE
Make IMU Internal Temperature Available in the existing UDP IMU buffer

### ISSUE THREAD

**Issue by arunumd** [ouster-lidar/ouster_example#576]
**Is your feature request related to a problem? Please describe.**
Currently the IMU's internal temperature data is not available as part of the IMU data buffer

**Describe the solution you'd like**
Hello, I am aware of the fact that TDK Invensense already provides temperature data for their IMU that comes with the Ouster OS1 Rev7 Model Lidar. But the [current Ouster IMU messages](https://static.ouster.dev/sensor-docs/image_route1/image_route3/sensor_data/sensor-data.html#imu-data-format) do not yet have this information populated. Currently the only way to get any kind of temperature data is through HTTP Request with the following command "_**GET /api/v1/sensor/telemetry**_". But this kind of HTTP request is very costly and comes at a very high response time due to the limitations of TCP connection. It would be excellent if you can populate the IMU's internal temperature into the IMU messages as part of the existing UDP transmissions.

**Describe alternatives you've considered**
I implemented a HTTP request for "**_GET /api/v1/sensor/telemetry_**". But this has led to packet losses due to the limitation of extended response time of HTTP connection.

**Targeted Platform (please complete the following information only if applicable, otherwise dot N/A):**
- Ouster Sensor? \[OS-1 Rev7\]
- Ouster Firmware Version? \[3.0.1\]
- Programming Language? \[C++\]
  - For Python include the targeted Python version \[NA\]
- Operating System? \[Windows 11\]
- Machine Architecture? \[x64 Intel\]

**Comment by twslankard** [comment]
Hi @arunumd !

Thanks for your enhancement request. Since this GitHub project is specific to Ouster SDK, I've forwarded your request to the Ouster Community site, which is also monitored by our firmware and product teams.

You can find a link here: https://community.ouster.com/t/make-imu-internal-temperature-available-in-the-existing-udp-imu-buffer/142

I hope this helps!

Cheers,

Tom Slankard
Staff Engineer
Ouster Inc.
