### ISSUE TITLE
some questions about ouster timestamp

### ISSUE THREAD

**Issue by ZhangYaoll** [ouster-lidar/ouster_example#584]
**Describe your question**
I use the python SDK to get data from source file(.pcap & .json).  In each packet, there are 3 kind of timestamps: capture_timestamp, timestamp(array with 16 elements) and host_timestamp. The first and last seem to be Unix timestamp, but what the second one is? How to translate it to UTC time?
Besides, each packet has 16 columns, and timestamp array has 16 elements, does it mean in every lidar scan, points share a same timestamp?

**Screenshots**
![20240326-160530](https://github.com/ouster-lidar/ouster_example/assets/53884785/f125a8c0-bd5f-4652-a1be-ea3c9f34f890)
![20240326-160555](https://github.com/ouster-lidar/ouster_example/assets/53884785/9731a0bf-b65b-4e0e-b1fb-29e979e88981)

**Platform (please complete the following information):**
- Ouster Sensor? \ OS-1 Rev6 128
- Ouster Firmware Version? \ 2.4
- Programming Language? \ Python 3.8
  - For Python include the targeted Python version
- Operating System?  Linux
- Machine Architecture?  x64
- git commit hash (if not the latest).

**Comment by Samahu** [comment]
The `timestamp` array holds the measurement timestamps according to the sensor internal clock or the time from the external clock when using PTP timestamp mode.

Please refer to the [setting sensor time source](https://static.ouster.dev/sensor-docs/image_route1/image_route2/time_sync/time-sync.html#setting-ouster-sensor-time-source) for more information on this topic.
Additionally, if you have other questions like this you can try to post them on the [ouster community forum](https://forum.ouster.com).
