### ISSUE TITLE
Object Detection on Point Cloud Data

### ISSUE THREAD

**Issue by jyothsna-phd22** [ouster-lidar/ouster_example#587]
Hi,

Has anyone worked on 3D object detection on point cloud data obtained from ouster lidar without converting to range image? Which tool is preferrable for annotation? Is there any code base to work on ouster data's object detection?

Kindly suggest me is any repos..

**Comment by Samahu** [comment]
@jyothsna-phd22 you can refer to the example provided in this repo: https://github.com/ouster-lidar/ouster-yolov5-demo, please note that this repo is pending an update https://github.com/ouster-lidar/ouster-yolov5-demo/pull/4 for the upcoming sdk release.

We also have another example on ouster's community portal https://community.ouster.com/t/running-yolo-on-2d-lidarscans-using-the-sdk/73 but this also requires the updated ouster-sdk which is due for release this week, so stay tuned :crossed_fingers:
