### ISSUE TITLE
Corner cases

### ISSUE THREAD

**Issue by asherikov** [ouster-lidar/ouster_example#59]
It appears that in all three of the following cases the lidar readings are zeroed out:
1. an obstacle is too close
2. an obstacle is out of range
3. azimuth block is bad
Am I correct? Is it possible to discreminate these cases somehow?

**Comment by dgarbuzov** [comment]
Currently there's no way to distinguish a lack of a return from a return being within the minimum range.

A bad azimuth block can be identified using the "azimuth data block status" field in each azimuth block. See the "lidar data format" section in your user guide.

**Comment by asherikov** [comment]
Block status info is missing in the point cloud, so basically all three cases are represented identically when using point clouds.

**Comment by dgarbuzov** [comment]
Correct me if I'm wrong, but I think `batch_to_iter` will skip adding points for invalid azimuth blocks entirely, whereas the other cases will show up as points at the origin.

Not sure that's super useful -- what would you like to see in the point cloud output?

**Comment by asherikov** [comment]
Probably, I haven't worked with it for a while. 
I've already refactored the node to match my specific needs. In general, I think, some sort of a range image could be more useful than a point cloud.
