### ISSUE TITLE
OS1 will not connect to Ouster studio

### ISSUE THREAD

**Issue by antithing** [ouster-lidar/ouster_example#593]
I have an OS1 sensor that has been in the box for a while. I have it connected (in windows., via a network switch) and I can ping it using:

`ping os1-9919201xxxxx.local`

```
Pinging os1-9919201xxxxx.local [fe80::be0f:a7ff:fe00:e8c%10] with 32 bytes of data:
Reply from fe80::be0f:a7ff:fe00:xxxxxx: time=1ms
Reply from fe80::be0f:a7ff:fe00:xxxxxx: time=1ms
Reply from fe80::be0f:a7ff:fe00:xxxxxx: time=1ms
Reply from fe80::be0f:a7ff:fe00:xxxxxx: time=1ms

```
However I cannot open the web browser UI, and ouster studio gives me:

'we found sensor xxxxx on your network but cannot connect to it yet. This usually happens when the sensor was just powered on'.

And it never connects.

Could this be a firmware issue? What can I do here?

Thanks!

**Comment by twslankard** [comment]
@antithing thank you for reaching out to us. This GitHub project is for the Ouster SDK.

For technical issues with Ouster equipment or software, please contact the Ouster Support Desk by submitting a ticket [here](https://ouster.atlassian.net/servicedesk/customer/portal/8) or by sending an email to [support@ouster.io](mailto:support@ouster.io).

Cheers,

Tom Slankard
Staff Engineer
Ouster Inc.
