### ISSUE TITLE
Ambient noise channel

### ISSUE THREAD

**Issue by alexandrx** [ouster-lidar/ouster_example#6]
First of all, thank you for the ROS node. I just tested it and works ok.

I added the "Ambient noise" channel output in your driver.
Here is the patch in case you're interested:
[ambient_noise_channel.txt](https://github.com/ouster-lidar/ouster_example/files/2277449/ambient_noise_channel.txt)

And here is a sample image:
![ambient_noise](https://user-images.githubusercontent.com/16696954/43951461-2f5ff6d4-9cce-11e8-9975-ebc68eb75bb1.png)

**Comment by rafficm** [comment]
Thanks Alex! We've updated this data feature, I'd encourage you to update your firmware and take another look at the ambient data. You can now also view it in the visualizer we posted last week in this repository.
