### ISSUE TITLE
split pcap file

### ISSUE THREAD

**Issue by moonmoonmoonmoon** [ouster-lidar/ouster_example#603]
Hello, everyone. I want to split a pcap file into multiple pcap files. Are there any APIs available to achieve this?

**Comment by Samahu** [comment]
Yes, you can use the slice command from ouster-cli to achieve this please refer to this [example](https://static.ouster.dev/sdk-docs/cli/sample-sessions.html#:~:text=If%20the%20slice%20is%20not%20present%20before%20save%2C%20you%20can%20stop%20recording%20at%20anytime%20with%20CTRL%2DC) in our latest doc.

Alternatively you can use the underlying python API to achieve this.

Hope this helps!
