### ISSUE TITLE
Unextractable Sensor noise due to reflection from road furnitures

### ISSUE THREAD

**Issue by Soumya-V-S** [ouster-lidar/ouster_example#61]
I am working with Ouster Lidar.During testing(outdoor as well as indoor ) a large amount of noise is observed around the road furniture due to its reflective material.There is no noise when the material is covered with non-reflective paper.Is there any mode/update in Ouster Lidar which will reduce the sensor noise from reflective materials?The screen shots are attached below.
![20190527_162545](https://user-images.githubusercontent.com/51072965/58416946-da790e00-80a0-11e9-9df9-a563818089fd.jpg)
The figure shows images of road furniture  with reflective material.

![20190527_162639](https://user-images.githubusercontent.com/51072965/58416976-f41a5580-80a0-11e9-9ea2-008bd225c6d7.jpg)
The figure shows the image with reflective material covered.
![20190524_160335](https://user-images.githubusercontent.com/51072965/58417129-7b67c900-80a1-11e9-95f0-8f06225b2a34.jpg)
The figure shows ouster lidar scan.The barricades are placed in front of lidar(Two objects in the middle). The scan in the left is from barricade with reflective material covered and scan in the right is the barricade with reflective material.  In the uncovered barricade a lot of noise is there in the front region and top area of the barricade.

**Comment by dllu** [comment]
The problem with retroreflectors should be improved with sensor firmware 1.12. See: https://www.ouster.io/downloads

![image](https://user-images.githubusercontent.com/14482624/58850253-8b078480-8642-11e9-80b7-fd9f459da743.png)
