### ISSUE TITLE
Check if saved points are in sync with PTP protocol

### ISSUE THREAD

**Issue by SamChuah** [ouster-lidar/ouster_example#63]
Hi all, 

How can I test or find out that my recorded data is actually in sync via PTP protocol? 

Thanks

**Comment by Ashik19** [comment]
Hi @SamChuah ,

Can you help me with one thing ? 

I am also trying to use the PTP to get the CPU time one the ouster timestamp but unfortunately when I am running the chronyc tracking command it tells me that 506 can not talk to daemon.

Any help will be very appreciated.

Thanks

**Comment by dgarbuzov** [comment]
Please contact ouster support for help configuring and integrating your lidar hardware
