### ISSUE TITLE
Running on windows?

### ISSUE THREAD

**Issue by antithing** [ouster-lidar/ouster_example#66]
Has anyone successfully connected to the os1 and streamed data on windows? I am having trouble.

**Comment by dllu** [comment]
It should be possible to compile `ouster_example` on Windows, but the newly released Ouster Studio may be easier to get set up for now: https://www.paraview.org/OusterStudio/

**Comment by mohit-khosti** [comment]
Hi @dllu 
You have a great knowledge about Ouster LiDAR sensors, so it would be very nice of you to join our Ouster forum https://forum.ouster.at/ where you can contribute to this newly created support facility for Ouster LiDAR!
