### ISSUE TITLE
Setting Up ROS Timestamps

### ISSUE THREAD

**Issue by oscarmendezm** [ouster-lidar/ouster_example#7]
Do you have some guidance on setting up the timestamps on the LiDAR to match those on ROS? This #1 talks about doing it, but I can't seem to figure it out.

 I understand it involves setting up a ptp master and enabling this functionality on the device, but I would like some general guidance on setting these things up.

**Comment by rafficm** [comment]
Hi Oscar, you can time sync either with PPS or PTP.  You can find an intro guide to PTP here - we recommend PTP4l 

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/deployment_guide/ch-configuring_ptp_using_ptp4l 

Let us know if you have any other questions!

Cheers,
Ouster
