### ISSUE TITLE
Not getting any ground point cloud

### ISSUE THREAD

**Issue by Ashik19** [ouster-lidar/ouster_example#71]
Hi,

I am using ouster os1-16 lidar unit. I am using it mounting on a car. When I am trying to render the point clouds from pcd into las file I am not getting any ground scan point clouds. Can anyone please tell me how to resolve this problem ? 

Thanks.

**Comment by dllu** [comment]
Did you check to make sure that the roof of the car is not blocking the field of view of the lidar?

**Comment by Ashik19** [comment]
Hi, @dllu thanks for your suggestion. Its's working well. I have some problems with the snesor configuration. But once I used the reset configuration it seems to be fine
