### ISSUE TITLE
Synchronize Jetson Xavier and Ouster Lidar

### ISSUE THREAD

**Issue by SamChuah** [ouster-lidar/ouster_example#76]
Hi, 
I am trying to collect some data using the NVIDIA Jetson Xavier. The Xavier has NIC that can be the master clock for PTP protocol. I am just wondering to synchronize between these two devices, do I just have to simply reconfigure the timestamp mode on Ouster Lidar to PTP and start the ptp4l before I running the lidar and data collection? Or there are some additional setups that need to be done?

**Comment by constructive-realities** [comment]
Yes essentially.  You do need to bind it to the right interface... you can also run it as a service to make it zero effort each time you use the lidar.

**Comment by mrgransky** [comment]
What does 
> binding to the right interface 

exactly mean?
Do you mean physical connection to the `multipurpose_io` port on the interface box?
