### ISSUE TITLE
how to run bag?(without radar)(only PC)

### ISSUE THREAD

**Issue by wzp171** [ouster-lidar/ouster_example#80]
I used the method of To publish ROS topics from recorded data. There is no replay of the contents of bag(2019-05-07-12-58-37_0.bag) in viz. I tried running the viz node of ouster_viz alone, using the sample-sensor-json package. However, the content in the bag is not replayed in OpenGL opened by the viz node.

**Comment by zuzi-m** [comment]
The `ouster_viz` package alone is supposed to work only with data coming in over the network from the sensor.
To replay contents of a ROS `.bag` file you need to use the `ouster_ros` package. It has a nice [README.md](https://github.com/ouster-lidar/ouster_example/blob/master/ouster_ros/README.md) file that will walk you through replaying data.

For more info, look at [this reply here](https://github.com/ouster-lidar/ouster_example/issues/103#issuecomment-523812982) that explains more details on how to play bag files and visualize it.
