### ISSUE TITLE
Running on Ubuntu Server? No Viz

### ISSUE THREAD

**Issue by BMannell** [ouster-lidar/ouster_example#85]
I'm trying to use the Ouster with a Raspberry Pi running a server version of Ubuntu (terminal only) but I run into errors when trying to compile the ouster_ros example. The errors always happen when trying to compile the ouster_viz package. How simple would it be to create a version of the ouster_ros example without the viz capabilities? Is it enough to just remove all reference of viz from the CMakeLists.txt file?

**Comment by dsb6063** [comment]
There was a post on this topic. You are correct. You have to remove the references to the rviz in the catkin package builder and cmake. There maybe robot packages on git that you may follow. Try the robots described here: wilselby.com/blog.



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by daniel-dsouza** [comment]
you can also try my fork which removes the visualization package and its dependencies, among other numerous changes.

**Comment by jo-ruch** [comment]
You can try to build only the packages you want with `catkin_make --pkg ouster_ros`
