### ISSUE TITLE
Check if Ouster is in sync with Jetson Xavier using ptp4l command

### ISSUE THREAD

**Issue by k-mohit** [ouster-lidar/ouster_example#89]
I set up my system with Ouster connected to Jetson Xavier and try to sync it by using ptp4l command. However, how can I check if the sensor is in synced?

**Comment by dsb6063** [comment]
Run the ouster client. Watch for the timestamp. It may take 1-2min.

**Comment by Chenweng1** [comment]
Hi @dsb6063 ,

Can you please tell me what are the full names of the following command and how I can save the data ?

![67537694_501066640627416_636020463956393984_n](https://user-images.githubusercontent.com/53556300/62273799-a51fd200-b3fb-11e9-8d52-2c94ff4f5967.jpg)

Thank you very much for your time.

Weng

**Comment by dsb6063** [comment]
_ts field is your timestamp. One for  the IMU and other for Sensor. Here is a site to show the current unix timestamp that you would expect to view. https://www.unixtimestamp.com/index.php



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by Chenweng1** [comment]
Hi @dsb6063 ,

So the first one is the imu timestamp and the third one is the point cloud timestamp ? Can you please tell what are the other 4 columns stand for ?

**Comment by dsb6063** [comment]
What you are looking for is bottom of page 18 and 19 showing the data format. This is found in the Software Manual on the downloads page. That will help. 

 

https://www.ouster.io/downloads

 



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus
