### ISSUE TITLE
error found ::  has no member named ‘floor’ 

### ISSUE THREAD

**Issue by praveenputhettu** [ouster-lidar/ouster_example#9]
when making 'ouster_viz' found the following error

/ouster_viz/src/viz.cpp:258:60: error: ‘class Eigen::Ref<Eigen::Array<double, -1, 1> >’ has no member named ‘floor’
             range_eigen = range_eigen * 1.01 - range_eigen.floor();

**Comment by dgarbuzov** [comment]
Can you provide at least the following details about your platform to help us debug: linux distro, compiler version, eigen library version. Thanks!
