### ISSUE TITLE
Ouster 64 cannot detect black squares in checker board

### ISSUE THREAD

**Issue by cynosure4sure** [ouster-lidar/ouster_example#91]
Hello!

I have a new ouster OS1-64 beam unit on firmware version 1.12.
I noticed a strange issue where ouster cannot detect objects of black color e.g. I placed some checkerboard patterns in front of the device and in both ouster visualization and rviz it cannot detect black squares. Please see images below for reference:
![Screenshot from 2019-08-02 19-26-04](https://user-images.githubusercontent.com/7845970/62406190-7d944b00-b55c-11e9-8a10-20d6f0e1fc66.png)

![Screenshot from 2019-08-02 19-27-35](https://user-images.githubusercontent.com/7845970/62406194-8dac2a80-b55c-11e9-9455-c0d44a55aaa5.png)

Similarly, in the rviz visualization if you see the intensity bounds in the side panel it shows a larger range as compared to other ouster units we have in the lab. 

My question would be do I have a defective unit? or am I setting some parameter on the device incorrectly?

Thank you.

**Comment by dsb6063** [comment]
That is quite interesting. In general, the color black absorbs light; therefore, the texture of the material would be helpful to understand your issue. Is it smooth, shiny and reflective, or dull and rough.  I would like hear the official response. We can usually track black targets with newer lasers but with some difficulty. Shiny black tends to be more difficult from using our equipment; however, rough texture tends to bounce and reflect more light. You may want to try adding texture to square just to see if it reflects any light.  Maybe shiny will work better?



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by cynosure4sure** [comment]
I contacted Ouster team and they said it is a known issue and they shared v1.13 beta version to resolve the issue. However, I haven't tested the new firmware on my unit yet.

**Comment by nicolasrosa** [comment]
Hello @cynosure4sure, did the firmware update solve the problem?
