### ISSUE TITLE
Software timestamping with ptp4l

### ISSUE THREAD

**Issue by Ashik19** [ouster-lidar/ouster_example#98]
HI, I have set my lidar timestamp mode to "Time_From_PTP-1588". After installing and initiating the ptp4l for software time stamping I am receiving the following error. Can anyone please tell me how to resolve this problem

![image](https://user-images.githubusercontent.com/52055757/63122080-28e0cf00-bf63-11e9-85d4-792c21ce54b9.png)

Thanks

**Comment by dsb6063** [comment]
In one of your config files. You are binding to port 53. Change it to 5353. 



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by Ashik19** [comment]
Can you please tell me where I can get the config file ?

sudo vim /lib/systemd/system/ptp4l.service running this command leading to the following window and my ouster network is eth0

![image](https://user-images.githubusercontent.com/52055757/63122688-93463f00-bf64-11e9-8cff-344768f03b7f.png)

**Comment by dsb6063** [comment]
If you used dnsmasq, I installed here. /etc/ 

sudo nano etc/dnsmasq.conf

check and verify port=5353 is not commented out.

Also, verify dnsmasq is working correctly. You should be able to connect the sensor directly and assign ip address automatically. 

Try this first. 
journalctl -fu dnsmasq

These will restart your services. Or reboot.

sudo systemctl daemon-reload
sudo systemctl restart ptp4l
sudo systemctl status ptp4l

sudo systemctl restart dnsmasq
sudo systemctl daemon-reload
sudo systemctl restart phc2sys
sudo systemctl status phc2sys

sudo systemctl start phc2shm
sudo systemctl status phc2shm

chronyc tracking

journalctl -fu dnsmasq

sudo ptp4l -i eno1 -m -H

**Comment by Ashik19** [comment]
Hi @dsb6063 ,

I am using dnsmasq. It's working fine and my sensor is also getting connected using the dnsmasq.
port is 5353
![image](https://user-images.githubusercontent.com/52055757/63128834-3d2cc800-bf73-11e9-93b2-18f19f6ae048.png)
 phc2shm
![image](https://user-images.githubusercontent.com/52055757/63128931-782efb80-bf73-11e9-93ee-3224ddc169f7.png)

phc2sys
![image](https://user-images.githubusercontent.com/52055757/63128999-af9da800-bf73-11e9-8aaa-f8fcaf25fc8f.png)

status ptp4l
![image](https://user-images.githubusercontent.com/52055757/63129088-dfe54680-bf73-11e9-8bc3-80760c528dd6.png)

"unknown option production description at line 83 in the eth0 section"

Can you please find any error in the process?

Thank you very much for your valuable time

**Comment by dsb6063** [comment]
I believe without knowing more about your setup that you are using one network card. remove the reference to the interface eth0 from line 83. Save and reboot.

**Comment by Ashik19** [comment]
Hi @dsb6063 ,

I have solved it we have to add -i (enterface name) in my case eth0 in the "sudo nano /etc/systemd/system/ptp4l.service.d/override.conf"

![image](https://user-images.githubusercontent.com/52055757/63137268-be478780-bf92-11e9-9173-ae5cb654b6f7.png)

But I don't understand when I am running the chronyc tracking it's saying. I have followed all the steps mentioned in the manual.

'506 can not talk to daemon'

**Comment by Ashik19** [comment]
HI @dsb6063 ,
I have followed all the steps through the manual.Unfortunately when I am running the chronyc tracking it's saying '506 can not talk to daemon'
![image](https://user-images.githubusercontent.com/52055757/63140195-539c4900-bf9e-11e9-93ac-5d5be53d653b.png)

 status ptp4l
![image](https://user-images.githubusercontent.com/52055757/63139994-927dcf00-bf9d-11e9-9549-ef93203aad8f.png)

status phc2sys
![image](https://user-images.githubusercontent.com/52055757/63140167-2cde1280-bf9e-11e9-9066-5322fad1f772.png)

status phc2shm
![image](https://user-images.githubusercontent.com/52055757/63140141-1768e880-bf9e-11e9-81f0-98b3b0dd5adc.png)

And when stamping the software getting the following message
![image](https://user-images.githubusercontent.com/52055757/63140227-74fd3500-bf9e-11e9-86c7-3b6fa0869b0b.png)

It would be very helpful if you couldguide me here

Thanks

**Comment by mrgransky** [comment]
For future reference, there's a `Search your computer` icon on the top left of your screen in `Ubuntu 16.04` and `Screenshot` application to avoid taking photo of your screen.

**Comment by yulan0215** [comment]
> HI, I have set my lidar timestamp mode to "Time_From_PTP-1588". After installing and initiating the ptp4l for software time stamping I am receiving the following error. Can anyone please tell me how to resolve this problem
> 
> ![image](https://user-images.githubusercontent.com/52055757/63122080-28e0cf00-bf63-11e9-85d4-792c21ce54b9.png)
> 
> Thanks

Hi, do you slove the problem of using PTP based on the software time stamping? I used Jetson Nano which could not support Hardware timestamping.
